/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;



/**
 *
 * @author mahen
 */
public class Add_users extends javax.swing.JFrame {

    /**
     * Creates new form Add_users
     */
    public Add_users() {
        initComponents();
        ImageIcon ic = new ImageIcon(getClass().getResource("/Icons/Tesla_Logo.png"));
        this.setIconImage(ic.getImage());
        this.setLocationRelativeTo(null);
    }
int x,y;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        base_au = new javax.swing.JPanel();
        au = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        des_au = new javax.swing.JTextField();
        dep_au = new javax.swing.JTextField();
        sal_au = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_img = new javax.swing.JLabel();
        Back1 = new javax.swing.JLabel();
        add_au = new javax.swing.JLabel();
        add_emp = new javax.swing.JLabel();
        add_cus = new javax.swing.JLabel();
        fn_au = new javax.swing.JTextField();
        ln_au = new javax.swing.JTextField();
        em_au = new javax.swing.JTextField();
        mn_au = new javax.swing.JTextField();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        pas_au = new javax.swing.JPasswordField();
        in_au = new javax.swing.JTextField();
        us_id = new javax.swing.JTextField();
        pic_us = new javax.swing.JLabel();
        insert_pic_au = new javax.swing.JLabel();
        Back_au = new javax.swing.JLabel();
        ac = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        lbl_img1 = new javax.swing.JLabel();
        insert_pic_au1 = new javax.swing.JLabel();
        add_cu = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        rbf_ac = new javax.swing.JRadioButton();
        rbm_ac = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        pic = new javax.swing.JLabel();
        insert_pic_ac = new javax.swing.JLabel();
        vari_ac = new javax.swing.JTextField();
        cus_id = new javax.swing.JTextField();
        ln_ac1 = new javax.swing.JTextField();
        pas_cus = new javax.swing.JPasswordField();
        autopilot_status = new javax.swing.JLabel();
        or_ac6 = new javax.swing.JTextField();
        or_ac7 = new javax.swing.JTextField();
        or_ac4 = new javax.swing.JTextField();
        or_ac3 = new javax.swing.JTextField();
        or_ac2 = new javax.swing.JTextField();
        or_ac1 = new javax.swing.JTextField();
        or_ac = new javax.swing.JTextField();
        mn_ac = new javax.swing.JTextField();
        em_ac = new javax.swing.JTextField();
        ln_ac = new javax.swing.JTextField();
        fn_ac = new javax.swing.JTextField();
        Close1 = new javax.swing.JLabel();
        Minimize1 = new javax.swing.JLabel();
        add_emp1 = new javax.swing.JLabel();
        add_cus1 = new javax.swing.JLabel();
        Back_ac = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_au.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                base_auMouseDragged(evt);
            }
        });
        base_au.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                base_auMousePressed(evt);
            }
        });
        base_au.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        au.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
        });
        au.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize.setForeground(new java.awt.Color(255, 255, 255));
        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizeMousePressed(evt);
            }
        });
        au.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        des_au.setBackground(new java.awt.Color(153, 0, 0));
        des_au.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        des_au.setForeground(new java.awt.Color(255, 255, 255));
        des_au.setBorder(null);
        au.add(des_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 280, 30));

        dep_au.setBackground(new java.awt.Color(153, 0, 0));
        dep_au.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dep_au.setForeground(new java.awt.Color(255, 255, 255));
        dep_au.setBorder(null);
        au.add(dep_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 270, 30));

        sal_au.setBackground(new java.awt.Color(153, 0, 0));
        sal_au.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sal_au.setForeground(new java.awt.Color(255, 255, 255));
        sal_au.setBorder(null);
        au.add(sal_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 310, 30));

        jDesktopPane1.setLayer(lbl_img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        au.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 150, 150));

        Back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Back1MousePressed(evt);
            }
        });
        au.add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 110, 50));

        add_au.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        au.add(add_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 670, 190, 40));

        add_emp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_empMousePressed(evt);
            }
        });
        au.add(add_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 200, 40));

        add_cus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_cus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_cusMousePressed(evt);
            }
        });
        au.add(add_cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 200, 40));

        fn_au.setBackground(new java.awt.Color(153, 0, 0));
        fn_au.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fn_au.setForeground(new java.awt.Color(255, 255, 255));
        fn_au.setBorder(null);
        au.add(fn_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 330, 20));

        ln_au.setBackground(new java.awt.Color(153, 0, 0));
        ln_au.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ln_au.setForeground(new java.awt.Color(255, 255, 255));
        ln_au.setBorder(null);
        au.add(ln_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 330, 20));

        em_au.setBackground(new java.awt.Color(153, 0, 0));
        em_au.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        em_au.setForeground(new java.awt.Color(255, 255, 255));
        em_au.setBorder(null);
        au.add(em_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 330, 20));

        mn_au.setBackground(new java.awt.Color(153, 0, 0));
        mn_au.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mn_au.setForeground(new java.awt.Color(255, 255, 255));
        mn_au.setBorder(null);
        au.add(mn_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 330, 20));

        r_male.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup2.add(r_male);
        r_male.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        r_male.setForeground(new java.awt.Color(255, 255, 255));
        r_male.setText("Male");
        r_male.setBorder(null);
        au.add(r_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        r_female.setBackground(new java.awt.Color(153, 0, 51));
        buttonGroup2.add(r_female);
        r_female.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        r_female.setForeground(new java.awt.Color(255, 255, 255));
        r_female.setText("Female");
        r_female.setBorder(null);
        au.add(r_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        jTextArea2.setBackground(new java.awt.Color(153, 0, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        au.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 390, 110));

        pas_au.setBackground(new java.awt.Color(153, 0, 51));
        pas_au.setBorder(null);
        pas_au.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pas_auActionPerformed(evt);
            }
        });
        au.add(pas_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 140, 20));

        in_au.setBackground(new java.awt.Color(153, 0, 0));
        in_au.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        in_au.setForeground(new java.awt.Color(255, 255, 255));
        in_au.setBorder(null);
        in_au.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_auActionPerformed(evt);
            }
        });
        au.add(in_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 140, 20));

        us_id.setBackground(new java.awt.Color(153, 0, 0));
        us_id.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        us_id.setForeground(new java.awt.Color(255, 255, 255));
        us_id.setBorder(null);
        au.add(us_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 130, 20));
        au.add(pic_us, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 140, 140));

        insert_pic_au.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        insert_pic_au.setText("             Add Photo");
        insert_pic_au.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insert_pic_au.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                insert_pic_auMousePressed(evt);
            }
        });
        au.add(insert_pic_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 140, 20));

        Back_au.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Add-Employee.png"))); // NOI18N
        au.add(Back_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        base_au.add(au, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        ac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(153, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        ac.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 390, 110));

        jDesktopPane2.setLayer(lbl_img1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        ac.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 150, 150));

        insert_pic_au1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        insert_pic_au1.setText("             Add Photo");
        insert_pic_au1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insert_pic_au1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                insert_pic_au1MousePressed(evt);
            }
        });
        ac.add(insert_pic_au1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 140, 20));

        add_cu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ac.add(add_cu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 670, 190, 40));

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
        });
        ac.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 110, 50));

        rbf_ac.setBackground(new java.awt.Color(153, 0, 51));
        buttonGroup1.add(rbf_ac);
        rbf_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbf_ac.setForeground(new java.awt.Color(255, 255, 255));
        rbf_ac.setText("Female");
        rbf_ac.setBorder(null);
        ac.add(rbf_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        rbm_ac.setBackground(new java.awt.Color(153, 0, 51));
        buttonGroup1.add(rbm_ac);
        rbm_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbm_ac.setForeground(new java.awt.Color(255, 255, 255));
        rbm_ac.setText("Male");
        rbm_ac.setBorder(null);
        ac.add(rbm_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(204, 51, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ac.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 530, 230, -1));
        ac.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 140, 140));
        ac.add(insert_pic_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 140, 20));

        vari_ac.setBackground(new java.awt.Color(204, 0, 0));
        vari_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        vari_ac.setForeground(new java.awt.Color(255, 255, 255));
        vari_ac.setBorder(null);
        ac.add(vari_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 616, 300, -1));

        cus_id.setBackground(new java.awt.Color(153, 0, 0));
        cus_id.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cus_id.setForeground(new java.awt.Color(255, 255, 255));
        cus_id.setBorder(null);
        ac.add(cus_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 130, 20));

        ln_ac1.setBackground(new java.awt.Color(153, 0, 0));
        ln_ac1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ln_ac1.setForeground(new java.awt.Color(255, 255, 255));
        ln_ac1.setBorder(null);
        ac.add(ln_ac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 140, 20));

        pas_cus.setBackground(new java.awt.Color(153, 0, 51));
        pas_cus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pas_cus.setBorder(null);
        pas_cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pas_cusActionPerformed(evt);
            }
        });
        ac.add(pas_cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 140, 20));
        ac.add(autopilot_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 90, 20));

        or_ac6.setBackground(new java.awt.Color(204, 0, 0));
        or_ac6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac6.setForeground(new java.awt.Color(255, 255, 255));
        or_ac6.setBorder(null);
        ac.add(or_ac6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 590, 250, 20));

        or_ac7.setBackground(new java.awt.Color(204, 0, 0));
        or_ac7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac7.setForeground(new java.awt.Color(255, 255, 255));
        or_ac7.setBorder(null);
        ac.add(or_ac7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 560, 180, 20));

        or_ac4.setBackground(new java.awt.Color(204, 0, 0));
        or_ac4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac4.setForeground(new java.awt.Color(255, 255, 255));
        or_ac4.setBorder(null);
        ac.add(or_ac4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 300, 20));

        or_ac3.setBackground(new java.awt.Color(204, 0, 0));
        or_ac3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac3.setForeground(new java.awt.Color(255, 255, 255));
        or_ac3.setBorder(null);
        ac.add(or_ac3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 450, 300, 20));

        or_ac2.setBackground(new java.awt.Color(204, 0, 0));
        or_ac2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac2.setForeground(new java.awt.Color(255, 255, 255));
        or_ac2.setBorder(null);
        ac.add(or_ac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 270, 20));

        or_ac1.setBackground(new java.awt.Color(204, 0, 0));
        or_ac1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac1.setForeground(new java.awt.Color(255, 255, 255));
        or_ac1.setBorder(null);
        ac.add(or_ac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 390, 280, 20));

        or_ac.setBackground(new java.awt.Color(204, 0, 0));
        or_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac.setForeground(new java.awt.Color(255, 255, 255));
        or_ac.setBorder(null);
        ac.add(or_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 280, 20));

        mn_ac.setBackground(new java.awt.Color(153, 0, 0));
        mn_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mn_ac.setForeground(new java.awt.Color(255, 255, 255));
        mn_ac.setBorder(null);
        ac.add(mn_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 330, 20));

        em_ac.setBackground(new java.awt.Color(153, 0, 0));
        em_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        em_ac.setForeground(new java.awt.Color(255, 255, 255));
        em_ac.setBorder(null);
        ac.add(em_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 330, 20));

        ln_ac.setBackground(new java.awt.Color(153, 0, 0));
        ln_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ln_ac.setForeground(new java.awt.Color(255, 255, 255));
        ln_ac.setBorder(null);
        ac.add(ln_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 330, 20));

        fn_ac.setBackground(new java.awt.Color(153, 0, 0));
        fn_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fn_ac.setForeground(new java.awt.Color(255, 255, 255));
        fn_ac.setBorder(null);
        ac.add(fn_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 330, 20));

        Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close1MousePressed(evt);
            }
        });
        ac.add(Close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize1MousePressed(evt);
            }
        });
        ac.add(Minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        add_emp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_emp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_emp1MousePressed(evt);
            }
        });
        ac.add(add_emp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 200, 40));

        add_cus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_cus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_cus1MousePressed(evt);
            }
        });
        ac.add(add_cus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 200, 40));

        Back_ac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Add-Customer2.png"))); // NOI18N
        ac.add(Back_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        base_au.add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(base_au, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMousePressed

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        // Close:
        System.exit(0);
    }//GEN-LAST:event_CloseMousePressed

    private void base_auMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_base_auMousePressed
        // Press Drag:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_base_auMousePressed

    private void base_auMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_base_auMouseDragged
        // Drag:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_base_auMouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Window Opener:
        try{
                    base_au.removeAll();
                    base_au.repaint();
                    base_au.revalidate();

                    base_au.add(au);
                    base_au.repaint();
                    base_au.revalidate();
               }catch(Exception e){
                 
               }
        
     
    }//GEN-LAST:event_formWindowOpened

    private void Close1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MousePressed
        // Close:
        System.exit(0);
    }//GEN-LAST:event_Close1MousePressed

    private void Minimize1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize1MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize1MousePressed

    private void add_cusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_cusMousePressed
        // set active to add_Cus
              try{ 
                    base_au.removeAll();
                    base_au.repaint();
                    base_au.revalidate();
                    //adding the target pannel
                    base_au.add(ac);
                    base_au.repaint();
                    base_au.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_add_cusMousePressed

    private void add_empMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_empMousePressed
        // set active to add_Emp
              try{ 
                    base_au.removeAll();
                    base_au.repaint();
                    base_au.revalidate();
                    //adding the target pannel
                    base_au.add(au);
                    base_au.repaint();
                    base_au.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_add_empMousePressed

    private void add_emp1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_emp1MousePressed
        // set active to add_Emp
              try{ 
                    base_au.removeAll();
                    base_au.repaint();
                    base_au.revalidate();
                    //adding the target pannel
                    base_au.add(au);
                    base_au.repaint();
                    base_au.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_add_emp1MousePressed

    private void add_cus1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_cus1MousePressed
        // set active to add_Cus
              try{ 
                    base_au.removeAll();
                    base_au.repaint();
                    base_au.revalidate();
                    //adding the target pannel
                    base_au.add(ac);
                    base_au.repaint();
                    base_au.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_add_cus1MousePressed

    private void pas_cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pas_cusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pas_cusActionPerformed

    private void pas_auActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pas_auActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pas_auActionPerformed

    private void in_auActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_auActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_auActionPerformed

    private void BackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMousePressed
        // Back:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_BackMousePressed

    private void Back1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MousePressed
        // Back:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    
          
    }//GEN-LAST:event_Back1MousePressed
//strin filename
    String filename = null;
    byte[] person_image = null;
    private void insert_pic_auMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insert_pic_auMousePressed
        // Add Photo
        JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
        filename =f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_DEFAULT));
        lbl_img.setIcon(imageIcon);
      try {

            File image = new File(filename);
            FileInputStream fis = new FileInputStream (image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){

                bos.write(buf,0,readNum);
            }
            person_image=bos.toByteArray();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
        
       
    
    }//GEN-LAST:event_insert_pic_auMousePressed

    private void insert_pic_au1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insert_pic_au1MousePressed
        // Add Photo
        JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
        filename =f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_DEFAULT));
        lbl_img.setIcon(imageIcon);
      try {

            File image = new File(filename);
            FileInputStream fis = new FileInputStream (image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){

                bos.write(buf,0,readNum);
            }
            person_image=bos.toByteArray();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_insert_pic_au1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_users().setVisible(true);
            }
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Back1;
    private javax.swing.JLabel Back_ac;
    private javax.swing.JLabel Back_au;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Close1;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Minimize1;
    private javax.swing.JPanel ac;
    private javax.swing.JLabel add_au;
    private javax.swing.JLabel add_cu;
    private javax.swing.JLabel add_cus;
    private javax.swing.JLabel add_cus1;
    private javax.swing.JLabel add_emp;
    private javax.swing.JLabel add_emp1;
    private javax.swing.JPanel au;
    private javax.swing.JLabel autopilot_status;
    private javax.swing.JPanel base_au;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cus_id;
    private javax.swing.JTextField dep_au;
    private javax.swing.JTextField des_au;
    private javax.swing.JTextField em_ac;
    private javax.swing.JTextField em_au;
    private javax.swing.JTextField fn_ac;
    private javax.swing.JTextField fn_au;
    private javax.swing.JTextField in_au;
    private javax.swing.JLabel insert_pic_ac;
    private javax.swing.JLabel insert_pic_au;
    private javax.swing.JLabel insert_pic_au1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_img1;
    private javax.swing.JTextField ln_ac;
    private javax.swing.JTextField ln_ac1;
    private javax.swing.JTextField ln_au;
    private javax.swing.JTextField mn_ac;
    private javax.swing.JTextField mn_au;
    private javax.swing.JTextField or_ac;
    private javax.swing.JTextField or_ac1;
    private javax.swing.JTextField or_ac2;
    private javax.swing.JTextField or_ac3;
    private javax.swing.JTextField or_ac4;
    private javax.swing.JTextField or_ac6;
    private javax.swing.JTextField or_ac7;
    private javax.swing.JPasswordField pas_au;
    private javax.swing.JPasswordField pas_cus;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel pic_us;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JRadioButton rbf_ac;
    private javax.swing.JRadioButton rbm_ac;
    private javax.swing.JTextField sal_au;
    private javax.swing.JTextField us_id;
    private javax.swing.JTextField vari_ac;
    // End of variables declaration//GEN-END:variables
}
