/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;

/**
 *
 * @author mahen
 */
public class Cus_Manager extends javax.swing.JFrame {

    /**
     * Creates new form Cus_Manager
     */
    public Cus_Manager() {
        initComponents();
        ImageIcon ic = new ImageIcon(getClass().getResource("/Icons/Tesla_Logo.png"));
        this.setIconImage(ic.getImage());
        this.setLocationRelativeTo(null);
    }
int x,y;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Minimize1 = new javax.swing.JLabel();
        Close1 = new javax.swing.JLabel();
        gen_cm = new javax.swing.JTextField();
        ln_ac = new javax.swing.JTextField();
        or_ac9 = new javax.swing.JTextField();
        mn_ac = new javax.swing.JTextField();
        cus_id = new javax.swing.JTextField();
        or_ac4 = new javax.swing.JTextField();
        or_ac2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        or_ac8 = new javax.swing.JTextField();
        fn_ac = new javax.swing.JTextField();
        em_ac = new javax.swing.JTextField();
        insert_pic_au1 = new javax.swing.JLabel();
        pas_cus = new javax.swing.JPasswordField();
        ln_ac1 = new javax.swing.JTextField();
        lbl_img1 = new javax.swing.JLabel();
        or_ac1 = new javax.swing.JTextField();
        or_ac3 = new javax.swing.JTextField();
        txt_search1 = new javax.swing.JTextField();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize1MousePressed(evt);
            }
        });
        jPanel1.add(Minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close1MousePressed(evt);
            }
        });
        jPanel1.add(Close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        gen_cm.setBackground(new java.awt.Color(153, 0, 0));
        gen_cm.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gen_cm.setForeground(new java.awt.Color(255, 255, 255));
        gen_cm.setBorder(null);
        jPanel1.add(gen_cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 330, 20));

        ln_ac.setBackground(new java.awt.Color(153, 0, 0));
        ln_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ln_ac.setForeground(new java.awt.Color(255, 255, 255));
        ln_ac.setBorder(null);
        jPanel1.add(ln_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 330, 20));

        or_ac9.setBackground(new java.awt.Color(204, 0, 0));
        or_ac9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac9.setForeground(new java.awt.Color(255, 255, 255));
        or_ac9.setBorder(null);
        or_ac9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                or_ac9ActionPerformed(evt);
            }
        });
        jPanel1.add(or_ac9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, 240, 20));

        mn_ac.setBackground(new java.awt.Color(153, 0, 0));
        mn_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mn_ac.setForeground(new java.awt.Color(255, 255, 255));
        mn_ac.setBorder(null);
        jPanel1.add(mn_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 330, 20));

        cus_id.setBackground(new java.awt.Color(153, 0, 0));
        cus_id.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cus_id.setForeground(new java.awt.Color(255, 255, 255));
        cus_id.setBorder(null);
        jPanel1.add(cus_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 130, 20));

        or_ac4.setBackground(new java.awt.Color(204, 0, 0));
        or_ac4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac4.setForeground(new java.awt.Color(255, 255, 255));
        or_ac4.setBorder(null);
        jPanel1.add(or_ac4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 280, 20));

        or_ac2.setBackground(new java.awt.Color(204, 0, 0));
        or_ac2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac2.setForeground(new java.awt.Color(255, 255, 255));
        or_ac2.setBorder(null);
        jPanel1.add(or_ac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 280, 20));

        jTextArea1.setBackground(new java.awt.Color(153, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 390, 110));

        or_ac8.setBackground(new java.awt.Color(204, 0, 0));
        or_ac8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac8.setForeground(new java.awt.Color(255, 255, 255));
        or_ac8.setBorder(null);
        or_ac8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                or_ac8ActionPerformed(evt);
            }
        });
        jPanel1.add(or_ac8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 230, 20));

        fn_ac.setBackground(new java.awt.Color(153, 0, 0));
        fn_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fn_ac.setForeground(new java.awt.Color(255, 255, 255));
        fn_ac.setBorder(null);
        jPanel1.add(fn_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 330, 20));

        em_ac.setBackground(new java.awt.Color(153, 0, 0));
        em_ac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        em_ac.setForeground(new java.awt.Color(255, 255, 255));
        em_ac.setBorder(null);
        jPanel1.add(em_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 330, 20));

        insert_pic_au1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        insert_pic_au1.setText("             Add Photo");
        insert_pic_au1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insert_pic_au1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                insert_pic_au1MousePressed(evt);
            }
        });
        jPanel1.add(insert_pic_au1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 140, 20));

        pas_cus.setBackground(new java.awt.Color(153, 0, 51));
        pas_cus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pas_cus.setBorder(null);
        pas_cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pas_cusActionPerformed(evt);
            }
        });
        jPanel1.add(pas_cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 140, 20));

        ln_ac1.setBackground(new java.awt.Color(153, 0, 0));
        ln_ac1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ln_ac1.setForeground(new java.awt.Color(255, 255, 255));
        ln_ac1.setBorder(null);
        jPanel1.add(ln_ac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 140, 20));
        jPanel1.add(lbl_img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 150, 145));

        or_ac1.setBackground(new java.awt.Color(204, 0, 0));
        or_ac1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac1.setForeground(new java.awt.Color(255, 255, 255));
        or_ac1.setBorder(null);
        jPanel1.add(or_ac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 280, 20));

        or_ac3.setBackground(new java.awt.Color(204, 0, 0));
        or_ac3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        or_ac3.setForeground(new java.awt.Color(255, 255, 255));
        or_ac3.setBorder(null);
        jPanel1.add(or_ac3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 250, 20));

        txt_search1.setBackground(new java.awt.Color(153, 0, 0));
        txt_search1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_search1.setText("  E n t e r C U S I D");
        txt_search1.setBorder(null);
        txt_search1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_search1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_search1FocusLost(evt);
            }
        });
        txt_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search1ActionPerformed(evt);
            }
        });
        txt_search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search1KeyReleased(evt);
            }
        });
        jPanel1.add(txt_search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 430, 40));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Manage_Customer.png"))); // NOI18N
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_search1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_search1FocusGained
        // Focus Gain
        if(txt_search1.getText().equals("  E n t e r C U S I D")){
            txt_search1.setText("");
        }
    }//GEN-LAST:event_txt_search1FocusGained

    private void txt_search1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_search1FocusLost
        // Focus Lost
        if(txt_search1.getText().equals("")){
            txt_search1.setText("  E n t e r C U S I D");
        }
    }//GEN-LAST:event_txt_search1FocusLost

    private void txt_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1ActionPerformed

    private void or_ac8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_or_ac8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_or_ac8ActionPerformed
    String filename = null;
    byte[] person_image = null;
    private void insert_pic_au1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insert_pic_au1MousePressed
        // Add Photo
        JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        filename =f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img1.getWidth(), lbl_img1.getHeight(), Image.SCALE_DEFAULT));
        lbl_img1.setIcon(imageIcon);
        try {

            File image = new File(filename);
            FileInputStream fis = new FileInputStream (image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){

                bos.write(buf,0,readNum);
            }
            person_image=bos.toByteArray();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_insert_pic_au1MousePressed

    private void pas_cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pas_cusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pas_cusActionPerformed

    private void or_ac9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_or_ac9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_or_ac9ActionPerformed

    private void txt_search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search1KeyReleased
        // Search:
        
        
    
    }//GEN-LAST:event_txt_search1KeyReleased

    private void Minimize1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize1MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize1MousePressed

    private void Close1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MousePressed
        // Close:
        System.exit(0);
    }//GEN-LAST:event_Close1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cus_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cus_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cus_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cus_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cus_Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Close1;
    private javax.swing.JLabel Minimize1;
    private javax.swing.JTextField cus_id;
    private javax.swing.JTextField em_ac;
    private javax.swing.JTextField fn_ac;
    private javax.swing.JTextField gen_cm;
    private javax.swing.JLabel insert_pic_au1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_img1;
    private javax.swing.JTextField ln_ac;
    private javax.swing.JTextField ln_ac1;
    private javax.swing.JTextField mn_ac;
    private javax.swing.JTextField or_ac1;
    private javax.swing.JTextField or_ac2;
    private javax.swing.JTextField or_ac3;
    private javax.swing.JTextField or_ac4;
    private javax.swing.JTextField or_ac8;
    private javax.swing.JTextField or_ac9;
    private javax.swing.JPasswordField pas_cus;
    private javax.swing.JTextField txt_search1;
    // End of variables declaration//GEN-END:variables
}
