package Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Mahi
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        Header.setBackground(new Color(240,240,240,75));
        dash_home.setBackground(new Color(240,240,240,75));
        ImageIcon ic = new ImageIcon(getClass().getResource("/Icons/Tesla_Logo.png"));
        this.setIconImage(ic.getImage());
        this.setLocationRelativeTo(null);
    }
    String active ="DashboardP";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sales = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        main_b = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        NavigationBar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DashboardP = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Inventory = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Users = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Vehicles = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Services = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Job_Card = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        userpic = new javax.swing.JLabel();
        Orders = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Reports = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        HEader = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        dash_home = new javax.swing.JPanel();
        Background = new javax.swing.JPanel();
        Cars_Label = new javax.swing.JLabel();
        Ser_Label = new javax.swing.JLabel();
        BK_Label = new javax.swing.JLabel();
        Emp_Label = new javax.swing.JLabel();
        Del_Label = new javax.swing.JLabel();
        Cus_Label = new javax.swing.JLabel();
        am = new javax.swing.JLabel();
        nb = new javax.swing.JLabel();
        anc = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        Back1 = new javax.swing.JLabel();
        inv_home = new javax.swing.JPanel();
        Base = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        us_home = new javax.swing.JPanel();
        Management = new javax.swing.JPanel();
        Pro = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Manage_Customer = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Add_Us = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        veh_home = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        s = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        X = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        service_home = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        job_home = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        orders_home = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        reports_home = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Footer = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        Sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalesMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Sales");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/shopping-bag.png"))); // NOI18N

        javax.swing.GroupLayout SalesLayout = new javax.swing.GroupLayout(Sales);
        Sales.setLayout(SalesLayout);
        SalesLayout.setHorizontalGroup(
            SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18)
                .addGap(26, 26, 26)
                .addComponent(jLabel17)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        SalesLayout.setVerticalGroup(
            SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1315, 1047));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_b.setBackground(new java.awt.Color(255, 255, 255));
        main_b.setPreferredSize(new java.awt.Dimension(1315, 1047));
        main_b.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                main_bMouseDragged(evt);
            }
        });
        main_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                main_bMousePressed(evt);
            }
        });
        main_b.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
        });
        main_b.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, -1, 29));

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizeMousePressed(evt);
            }
        });
        main_b.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 30, 29));

        NavigationBar.setBackground(new java.awt.Color(204, 0, 0));
        NavigationBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/tesla01.png"))); // NOI18N
        NavigationBar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 25));

        DashboardP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DashboardP.setPreferredSize(new java.awt.Dimension(190, 50));
        DashboardP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DashboardPMousePressed(evt);
            }
        });
        DashboardP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home(1).png"))); // NOI18N
        DashboardP.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 23, 28));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Dashboard");
        DashboardP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        NavigationBar.add(DashboardP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 190, 50));

        Inventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InventoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InventoryMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/inventory.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Inventory");

        javax.swing.GroupLayout InventoryLayout = new javax.swing.GroupLayout(Inventory);
        Inventory.setLayout(InventoryLayout);
        InventoryLayout.setHorizontalGroup(
            InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        InventoryLayout.setVerticalGroup(
            InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        NavigationBar.add(Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 190, 50));

        Users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsersMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/followers.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Users");

        javax.swing.GroupLayout UsersLayout = new javax.swing.GroupLayout(Users);
        Users.setLayout(UsersLayout);
        UsersLayout.setHorizontalGroup(
            UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        UsersLayout.setVerticalGroup(
            UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        NavigationBar.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 190, 50));

        Vehicles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Vehicles.setPreferredSize(new java.awt.Dimension(190, 50));
        Vehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VehiclesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VehiclesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VehiclesMousePressed(evt);
            }
        });
        Vehicles.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sedan-car-model.png"))); // NOI18N
        Vehicles.add(jLabel12);
        jLabel12.setBounds(19, 11, 32, 32);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Vehicles");
        Vehicles.add(jLabel11);
        jLabel11.setBounds(77, 11, 60, 32);

        NavigationBar.add(Vehicles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        Services.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Services.setPreferredSize(new java.awt.Dimension(190, 50));
        Services.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ServicesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ServicesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ServicesMousePressed(evt);
            }
        });
        Services.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon.png"))); // NOI18N
        Services.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 23, 28));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Services");
        Services.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        NavigationBar.add(Services, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 190, 50));

        Job_Card.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Job_Card.setPreferredSize(new java.awt.Dimension(190, 50));
        Job_Card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Job_CardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Job_CardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Job_CardMousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Job Card");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/shopping-list.png"))); // NOI18N

        javax.swing.GroupLayout Job_CardLayout = new javax.swing.GroupLayout(Job_Card);
        Job_Card.setLayout(Job_CardLayout);
        Job_CardLayout.setHorizontalGroup(
            Job_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Job_CardLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        Job_CardLayout.setVerticalGroup(
            Job_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Job_CardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Job_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        NavigationBar.add(Job_Card, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, -1, 50));

        userpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user_round.png"))); // NOI18N
        NavigationBar.add(userpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, 110));

        usernamelabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        NavigationBar.add(usernamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 70, 20));

        Orders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Orders.setPreferredSize(new java.awt.Dimension(190, 50));
        Orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OrdersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OrdersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OrdersMousePressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Orders");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/shopping-bag.png"))); // NOI18N

        javax.swing.GroupLayout OrdersLayout = new javax.swing.GroupLayout(Orders);
        Orders.setLayout(OrdersLayout);
        OrdersLayout.setHorizontalGroup(
            OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdersLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel25)
                .addGap(26, 26, 26)
                .addComponent(jLabel24)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        OrdersLayout.setVerticalGroup(
            OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        NavigationBar.add(Orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, -1, -1));

        Reports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reports.setPreferredSize(new java.awt.Dimension(190, 50));
        Reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReportsMousePressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setText("Reports");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/analytics.png"))); // NOI18N

        javax.swing.GroupLayout ReportsLayout = new javax.swing.GroupLayout(Reports);
        Reports.setLayout(ReportsLayout);
        ReportsLayout.setHorizontalGroup(
            ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel27)
                .addGap(26, 26, 26)
                .addComponent(jLabel26)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        ReportsLayout.setVerticalGroup(
            ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        NavigationBar.add(Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, -1));

        main_b.add(NavigationBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 1050));

        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HEader.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        HEader.setText("Automotive Management System");
        Header.add(HEader, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 502, 37));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu.png"))); // NOI18N
        Header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 40));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow.png"))); // NOI18N
        jLabel48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel48MousePressed(evt);
            }
        });
        Header.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 30, 40));

        main_b.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 1060, 80));

        main.setPreferredSize(new java.awt.Dimension(1060, 840));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setLayout(null);

        Cars_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Background.add(Cars_Label);
        Cars_Label.setBounds(310, 500, 120, 40);

        Ser_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Background.add(Ser_Label);
        Ser_Label.setBounds(580, 500, 100, 40);

        BK_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Background.add(BK_Label);
        BK_Label.setBounds(830, 500, 100, 40);

        Emp_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Background.add(Emp_Label);
        Emp_Label.setBounds(850, 700, 90, 30);

        Del_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Background.add(Del_Label);
        Del_Label.setBounds(320, 690, 100, 30);

        Cus_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Background.add(Cus_Label);
        Cus_Label.setBounds(590, 690, 100, 30);

        am.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        am.setText("           Add Maintainance ");
        am.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        am.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                amMousePressed(evt);
            }
        });
        Background.add(am);
        am.setBounds(420, 220, 250, 110);

        nb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nb.setText("        Add New Booking");
        nb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nbMousePressed(evt);
            }
        });
        Background.add(nb);
        nb.setBounds(110, 200, 250, 130);

        anc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        anc.setText("          Add New Customer ");
        anc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ancMousePressed(evt);
            }
        });
        Background.add(anc);
        anc.setBounds(740, 220, 250, 110);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Dash-12.png"))); // NOI18N
        Background.add(Back);
        Back.setBounds(0, 0, 1060, 850);

        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Dash1.gif"))); // NOI18N
        Background.add(Back1);
        Back1.setBounds(0, 0, 1060, 850);

        javax.swing.GroupLayout dash_homeLayout = new javax.swing.GroupLayout(dash_home);
        dash_home.setLayout(dash_homeLayout);
        dash_homeLayout.setHorizontalGroup(
            dash_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dash_homeLayout.setVerticalGroup(
            dash_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        main.add(dash_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 850));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Model ID", "Name", "Manufacture Year", "Chassis Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("All Models", jPanel3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Available Stock", jPanel5);

        javax.swing.GroupLayout BaseLayout = new javax.swing.GroupLayout(Base);
        Base.setLayout(BaseLayout);
        BaseLayout.setHorizontalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        BaseLayout.setVerticalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("All Models");

        javax.swing.GroupLayout inv_homeLayout = new javax.swing.GroupLayout(inv_home);
        inv_home.setLayout(inv_homeLayout);
        inv_homeLayout.setHorizontalGroup(
            inv_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        inv_homeLayout.setVerticalGroup(
            inv_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main.add(inv_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 850));

        Management.setBackground(new java.awt.Color(204, 0, 51));
        Management.setMinimumSize(new java.awt.Dimension(1060, 850));
        Management.setPreferredSize(new java.awt.Dimension(1060, 850));
        Management.setLayout(null);

        Pro.setBackground(new java.awt.Color(255, 255, 255));
        Pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProMousePressed(evt);
            }
        });
        Pro.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel35.setText("User Profiles");
        Pro.add(jLabel35);
        jLabel35.setBounds(90, 130, 100, 17);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/curriculum.png"))); // NOI18N
        Pro.add(jLabel39);
        jLabel39.setBounds(110, 40, 70, 70);

        Management.add(Pro);
        Pro.setBounds(371, 291, 290, 170);

        Manage_Customer.setBackground(new java.awt.Color(255, 255, 255));
        Manage_Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Manage_CustomerMousePressed(evt);
            }
        });
        Manage_Customer.setLayout(null);

        jLabel44.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel44.setText("Manage Customers");
        Manage_Customer.add(jLabel44);
        jLabel44.setBounds(70, 130, 150, 17);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/businessman(2).png"))); // NOI18N
        Manage_Customer.add(jLabel45);
        jLabel45.setBounds(110, 44, 70, 70);

        Management.add(Manage_Customer);
        Manage_Customer.setBounds(60, 290, 290, 170);

        Add_Us.setBackground(new java.awt.Color(255, 255, 255));
        Add_Us.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Add_UsMousePressed(evt);
            }
        });
        Add_Us.setLayout(null);

        jLabel38.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel38.setText("Add Users");
        Add_Us.add(jLabel38);
        jLabel38.setBounds(110, 130, 80, 17);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/add-user(1).png"))); // NOI18N
        Add_Us.add(jLabel40);
        jLabel40.setBounds(110, 44, 70, 70);

        Management.add(Add_Us);
        Add_Us.setBounds(679, 291, 290, 170);

        javax.swing.GroupLayout us_homeLayout = new javax.swing.GroupLayout(us_home);
        us_home.setLayout(us_homeLayout);
        us_homeLayout.setHorizontalGroup(
            us_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Management, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        us_homeLayout.setVerticalGroup(
            us_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Management, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main.add(us_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 850));

        veh_home.setPreferredSize(new java.awt.Dimension(1060, 850));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(null);

        s.setBackground(new java.awt.Color(255, 255, 255));
        s.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sMousePressed(evt);
            }
        });
        s.setLayout(null);

        jLabel34.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel34.setText("Model S");
        s.add(jLabel34);
        jLabel34.setBounds(110, 130, 60, 17);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hero-high-viewport.png"))); // NOI18N
        s.add(jLabel41);
        jLabel41.setBounds(0, 40, 290, 90);

        jPanel6.add(s);
        s.setBounds(70, 410, 289, 173);

        X.setBackground(new java.awt.Color(255, 255, 255));
        X.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XMousePressed(evt);
            }
        });
        X.setLayout(null);

        jLabel42.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel42.setText("Model X");
        X.add(jLabel42);
        jLabel42.setBounds(110, 130, 70, 17);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hero-high-viewport@2.png"))); // NOI18N
        X.add(jLabel43);
        jLabel43.setBounds(30, 30, 240, 100);

        jPanel6.add(X);
        X.setBounds(650, 420, 290, 170);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Images/hero-ms-INventory.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7);
        jPanel7.setBounds(0, 0, 1060, 112);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Veh.png"))); // NOI18N
        jPanel6.add(jLabel20);
        jLabel20.setBounds(0, 110, 1060, 740);

        javax.swing.GroupLayout veh_homeLayout = new javax.swing.GroupLayout(veh_home);
        veh_home.setLayout(veh_homeLayout);
        veh_homeLayout.setHorizontalGroup(
            veh_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
        );
        veh_homeLayout.setVerticalGroup(
            veh_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        main.add(veh_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 850));

        jPanel11.setPreferredSize(new java.awt.Dimension(1060, 850));
        jPanel11.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Service.gif"))); // NOI18N
        jLabel23.setText("jLabel21");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel12);
        jPanel12.setBounds(0, 0, 1060, 850);

        javax.swing.GroupLayout service_homeLayout = new javax.swing.GroupLayout(service_home);
        service_home.setLayout(service_homeLayout);
        service_homeLayout.setHorizontalGroup(
            service_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        service_homeLayout.setVerticalGroup(
            service_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 1590, Short.MAX_VALUE)
        );

        main.add(service_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2120, 1590));

        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 850));
        jPanel1.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Job.png"))); // NOI18N
        jLabel21.setText("jLabel21");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(0, 0, 1060, 850);

        javax.swing.GroupLayout job_homeLayout = new javax.swing.GroupLayout(job_home);
        job_home.setLayout(job_homeLayout);
        job_homeLayout.setHorizontalGroup(
            job_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        job_homeLayout.setVerticalGroup(
            job_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main.add(job_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(1060, 850));
        jPanel2.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/orders_home.png"))); // NOI18N
        jLabel28.setText("jLabel21");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel10);
        jPanel10.setBounds(0, 0, 1060, 850);

        javax.swing.GroupLayout orders_homeLayout = new javax.swing.GroupLayout(orders_home);
        orders_home.setLayout(orders_homeLayout);
        orders_homeLayout.setHorizontalGroup(
            orders_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        orders_homeLayout.setVerticalGroup(
            orders_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main.add(orders_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setPreferredSize(new java.awt.Dimension(1060, 850));
        jPanel4.setLayout(null);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Reports.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel13);
        jPanel13.setBounds(0, 0, 1060, 850);

        javax.swing.GroupLayout reports_homeLayout = new javax.swing.GroupLayout(reports_home);
        reports_home.setLayout(reports_homeLayout);
        reports_homeLayout.setHorizontalGroup(
            reports_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        reports_homeLayout.setVerticalGroup(
            reports_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main.add(reports_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_b.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 1060, 850));

        jSeparator1.setBackground(new java.awt.Color(204, 0, 0));
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 10));
        main_b.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 1060, 10));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("All Rights Reserved by Automotive Management System");

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(789, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(20, 20, 20))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        main_b.add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1010, 1130, -1));

        getContentPane().add(main_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_bMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_bMousePressed
        // Press Drag:
        x=evt.getX();
        y=evt.getY();

    }//GEN-LAST:event_main_bMousePressed

    private void main_bMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_bMouseDragged
        // Drag:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_main_bMouseDragged

    private void MinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMousePressed

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        // Close:
        System.exit(0);
    }//GEN-LAST:event_CloseMousePressed

    private void DashboardPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardPMouseEntered
        // Colour Entry:
        DashboardP.setBackground(new Color(255,204,204));
        
    }//GEN-LAST:event_DashboardPMouseEntered

    private void DashboardPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardPMouseExited
        // Colour Exit:
        if( !(active.equalsIgnoreCase("DashboardP")) ){
        DashboardP.setBackground(new Color(240,240,240));}
    }//GEN-LAST:event_DashboardPMouseExited

    private void InventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseEntered
        // Colour Entry:
        Inventory.setBackground(new Color(255,204,204));
        
    }//GEN-LAST:event_InventoryMouseEntered

    private void InventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseExited
        // Colour Exit:
        if(!(active.equalsIgnoreCase("Inventory"))){
        Inventory.setBackground(new Color(240,240,240));}
    }//GEN-LAST:event_InventoryMouseExited

    private void UsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseEntered
        // Colour Entry:
        Users.setBackground(new Color(255,204,204));
        
    }//GEN-LAST:event_UsersMouseEntered

    private void UsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseExited
        // Colour Exit:
        if(!(active.equalsIgnoreCase("Users"))){
        Users.setBackground(new Color(240,240,240));}
    }//GEN-LAST:event_UsersMouseExited

    private void VehiclesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehiclesMouseEntered
        // Colour Entry:
        Vehicles.setBackground(new Color(255,204,204));
        
    }//GEN-LAST:event_VehiclesMouseEntered

    private void VehiclesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehiclesMouseExited
        // Colour Exit:
        if(!(active.equalsIgnoreCase("Vehicles"))){
        Vehicles.setBackground(new Color(240,240,240));}
    }//GEN-LAST:event_VehiclesMouseExited

    private void ServicesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicesMouseEntered
        //Colour Entry:
        Services.setBackground(new Color(255,204,204));
        
    }//GEN-LAST:event_ServicesMouseEntered

    private void ServicesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicesMouseExited
        // Colour Exit:
        if(!(active.equalsIgnoreCase("Services"))){
        Services.setBackground(new Color(240,240,240));}
    }//GEN-LAST:event_ServicesMouseExited

    private void Job_CardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Job_CardMouseEntered
        // Colour Entry:
        Job_Card.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_Job_CardMouseEntered

    private void Job_CardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Job_CardMouseExited
        // Colour Exit:
        
        if(!(active.equalsIgnoreCase("Job_Card"))){
        Job_Card.setBackground(new Color(240,240,240));}
    }//GEN-LAST:event_Job_CardMouseExited

    private void SalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesMouseEntered
        // Colour Entry:
        Sales.setBackground(new Color(240,204,204));
        
    }//GEN-LAST:event_SalesMouseEntered

    private void SalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesMouseExited
        // Colour Exit:
        if(!(active.equalsIgnoreCase("Sales"))){
        Sales.setBackground(new Color(240,240,240));}
    }//GEN-LAST:event_SalesMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Window Opener:
        try{
                    main.removeAll();
                    main.repaint();
                    main.revalidate();

                    main.add(dash_home);
                    main.repaint();
                    main.revalidate();
               }catch(Exception e){
                 
               }
        
    }//GEN-LAST:event_formWindowOpened

    private void DashboardPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardPMousePressed
        // set active to add
            active= "DashboardP";
            DashboardP.setBackground(new Color(240,204,204));
            Inventory.setBackground(new Color(240,240,240));
            Users.setBackground(new Color(240,240,240));
            Vehicles.setBackground(new Color(240,240,240));
            Services.setBackground(new Color(240,240,240));
            Job_Card.setBackground(new Color(240,240,240));
            Orders.setBackground(new Color(240,240,240));
            Reports.setBackground(new Color(240,240,240));
            //setting active
              try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(dash_home);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_DashboardPMousePressed

    private void InventoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMousePressed
        // Act Inventory:
        active= "Inventory";
            DashboardP.setBackground(new Color(240,240,240));
            Inventory.setBackground(new Color(240,204,204));
            Users.setBackground(new Color(240,240,240));
            Vehicles.setBackground(new Color(240,240,240));
            Services.setBackground(new Color(240,240,240));
            Job_Card.setBackground(new Color(240,240,240));
            Orders.setBackground(new Color(240,240,240));
            Reports.setBackground(new Color(240,240,240));

            //setting active
              try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(inv_home);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_InventoryMousePressed

    private void UsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMousePressed
        // Act User:
        active= "Users";
            DashboardP.setBackground(new Color(240,240,240));
            Inventory.setBackground(new Color(240,240,240));
            Users.setBackground(new Color(240,204,204));
            Vehicles.setBackground(new Color(240,240,240));
            Services.setBackground(new Color(240,240,240));
            Job_Card.setBackground(new Color(240,240,240));
            Orders.setBackground(new Color(240,240,240));
            Reports.setBackground(new Color(240,240,240));
        
            //setting active
              try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(us_home);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_UsersMousePressed

    private void VehiclesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehiclesMousePressed
        // Act Vehicle:
        active= "Vehicles";
            DashboardP.setBackground(new Color(240,240,240));
            Inventory.setBackground(new Color(240,240,240));
            Users.setBackground(new Color(240,240,240));
            Vehicles.setBackground(new Color(240,204,204));
            Services.setBackground(new Color(240,240,240));
            Job_Card.setBackground(new Color(240,240,240));
            Orders.setBackground(new Color(240,240,240));
            Reports.setBackground(new Color(240,240,240));
            //setting active
              try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(veh_home);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_VehiclesMousePressed

    private void ServicesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicesMousePressed
        // Act Service:
        active= "Services";
            DashboardP.setBackground(new Color(240,240,240));
            Inventory.setBackground(new Color(240,240,240));
            Users.setBackground(new Color(240,240,240));
            Vehicles.setBackground(new Color(240,240,240));
            Services.setBackground(new Color(240,204,204));
            Job_Card.setBackground(new Color(240,240,240));
            Orders.setBackground(new Color(240,240,240));
            Reports.setBackground(new Color(240,240,240));
            //setting active
              try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(service_home);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_ServicesMousePressed

    private void Job_CardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Job_CardMousePressed
        // Act Dashboard:
        active= "Job_Card";
            DashboardP.setBackground(new Color(240,240,240));
            Inventory.setBackground(new Color(240,240,240));
            Users.setBackground(new Color(240,240,240));
            Vehicles.setBackground(new Color(240,240,240));
            Services.setBackground(new Color(240,240,240));
            Job_Card.setBackground(new Color(240,204,204));
            Orders.setBackground(new Color(240,240,240));
            Reports.setBackground(new Color(240,240,240));
            //setting active
              try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(job_home);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_Job_CardMousePressed

    private void sMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sMouseEntered

    private void sMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sMouseExited

    private void sMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMousePressed
        // Model S Open:
        Model_S ms = new Model_S();
        ms.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMousePressed

    private void jLabel48MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MousePressed
        // Logout:
        
        
    }//GEN-LAST:event_jLabel48MousePressed

    private void XMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMousePressed
        // Model X Open:
        Model_X mx = new Model_X();
        mx.setVisible(true);
        dispose();
    }//GEN-LAST:event_XMousePressed

    private void ProMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProMousePressed
        // Show admin Profiles:
        Profiles pf = new Profiles();
        pf.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProMousePressed

    private void nbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nbMousePressed
        // setting active Vehicles
              try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(veh_home);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
    }//GEN-LAST:event_nbMousePressed
    }
    private void amMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amMousePressed
        // setting active Vehicles
              try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(service_home);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
    }//GEN-LAST:event_amMousePressed
    } 
    private void ancMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ancMousePressed
        //Show Customer_Manager:
        Add_users as = new Add_users();
        as.setVisible(true);
        dispose();
    
    }//GEN-LAST:event_ancMousePressed

    private void Add_UsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_UsMousePressed
        // Show admin Profiles:
        Add_users au = new Add_users();
        au.setVisible(true);
        dispose();
    }//GEN-LAST:event_Add_UsMousePressed

    private void Manage_CustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Manage_CustomerMousePressed
        //Show Customer_Manager:
        Cus_Manager cm = new Cus_Manager();
        cm.setVisible(true);
        dispose();
    }//GEN-LAST:event_Manage_CustomerMousePressed

    private void OrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersMouseEntered
         // Colour Entry:
        Orders.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_OrdersMouseEntered

    private void OrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersMouseExited
        // Colour Exit:
        
        if(!(active.equalsIgnoreCase("Orders"))){
        Orders.setBackground(new Color(240,240,240));}
    }//GEN-LAST:event_OrdersMouseExited

    private void OrdersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersMousePressed
        // Act Orders:
        active= "Orders";
            DashboardP.setBackground(new Color(240,240,240));
            Inventory.setBackground(new Color(240,240,240));
            Users.setBackground(new Color(240,240,240));
            Vehicles.setBackground(new Color(240,240,240));
            Services.setBackground(new Color(240,240,240));
            Job_Card.setBackground(new Color(240,240,240));
            Orders.setBackground(new Color(255,204,204));
            Reports.setBackground(new Color(240,240,240));
            //setting active
              try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(orders_home);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_OrdersMousePressed

    private void ReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseEntered
        // Colour Entry:
        Reports.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_ReportsMouseEntered

    private void ReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseExited
        // Colour Exit:
        
        if(!(active.equalsIgnoreCase("Reports"))){
        Reports.setBackground(new Color(240,240,240));}
    }//GEN-LAST:event_ReportsMouseExited

    private void ReportsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMousePressed
        // Act Reports:
        active= "Reports";
            DashboardP.setBackground(new Color(240,240,240));
            Inventory.setBackground(new Color(240,240,240));
            Users.setBackground(new Color(240,240,240));
            Vehicles.setBackground(new Color(240,240,240));
            Services.setBackground(new Color(240,240,240));
            Job_Card.setBackground(new Color(240,240,240));
            Orders.setBackground(new Color(240,240,240));
            Reports.setBackground(new Color(240,204,204));
            //setting active
              try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(reports_home);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_ReportsMousePressed
int x,y;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_Us;
    private javax.swing.JLabel BK_Label;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Back1;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Base;
    private javax.swing.JLabel Cars_Label;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Cus_Label;
    private javax.swing.JPanel DashboardP;
    private javax.swing.JLabel Del_Label;
    private javax.swing.JLabel Emp_Label;
    private javax.swing.JPanel Footer;
    private javax.swing.JLabel HEader;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Inventory;
    private javax.swing.JPanel Job_Card;
    private javax.swing.JPanel Manage_Customer;
    private javax.swing.JPanel Management;
    private javax.swing.JLabel Minimize;
    private javax.swing.JPanel NavigationBar;
    private javax.swing.JPanel Orders;
    private javax.swing.JPanel Pro;
    private javax.swing.JPanel Reports;
    private javax.swing.JPanel Sales;
    private javax.swing.JLabel Ser_Label;
    private javax.swing.JPanel Services;
    private javax.swing.JPanel Users;
    private javax.swing.JPanel Vehicles;
    private javax.swing.JPanel X;
    private javax.swing.JLabel am;
    private javax.swing.JLabel anc;
    private javax.swing.JPanel dash_home;
    private javax.swing.JPanel inv_home;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel job_home;
    private javax.swing.JPanel main;
    private javax.swing.JPanel main_b;
    private javax.swing.JLabel nb;
    private javax.swing.JPanel orders_home;
    private javax.swing.JPanel reports_home;
    private javax.swing.JPanel s;
    private javax.swing.JPanel service_home;
    private javax.swing.JPanel us_home;
    public static final javax.swing.JLabel usernamelabel = new javax.swing.JLabel();
    private javax.swing.JLabel userpic;
    private javax.swing.JPanel veh_home;
    // End of variables declaration//GEN-END:variables

    }
