/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import javax.swing.ImageIcon;
import java.awt.Color;

/**
 *
 * @author mahen
 */
public class Model_X extends javax.swing.JFrame {

    /**
     * Creates new form Model_X
     */
    public Model_X() {
        initComponents();
        ImageIcon ic = new ImageIcon(getClass().getResource("/Icons/Tesla_Logo.png"));
        this.setIconImage(ic.getImage());
    }
    String active ="Safety";
int x,y;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sub_x = new javax.swing.JPanel();
        main_x = new javax.swing.JPanel();
        model_home_X = new javax.swing.JPanel();
        Base_X = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        jLabel2_x = new javax.swing.JLabel();
        Background_x = new javax.swing.JLabel();
        safety_X = new javax.swing.JPanel();
        Base_2_x = new javax.swing.JPanel();
        Close8 = new javax.swing.JLabel();
        Minimize8 = new javax.swing.JLabel();
        jLabel3_x = new javax.swing.JLabel();
        safe_pan_x = new javax.swing.JLabel();
        range_x = new javax.swing.JPanel();
        base_4_x = new javax.swing.JPanel();
        Close6 = new javax.swing.JLabel();
        Minimize6 = new javax.swing.JLabel();
        jLabel6_x = new javax.swing.JLabel();
        jLabel7_x = new javax.swing.JLabel();
        autopilot_x = new javax.swing.JPanel();
        base_5_x = new javax.swing.JPanel();
        Close5 = new javax.swing.JLabel();
        Minimize5 = new javax.swing.JLabel();
        jLabel8_x = new javax.swing.JLabel();
        jLabel9_x = new javax.swing.JLabel();
        performance_x = new javax.swing.JPanel();
        base_3_x = new javax.swing.JPanel();
        Close7 = new javax.swing.JLabel();
        Minimize7 = new javax.swing.JLabel();
        jLabel5_x = new javax.swing.JLabel();
        jLabel4_x = new javax.swing.JLabel();
        interior_x = new javax.swing.JPanel();
        base_6_x = new javax.swing.JPanel();
        Close4 = new javax.swing.JLabel();
        Minimize4 = new javax.swing.JLabel();
        jLabel10_x = new javax.swing.JLabel();
        jLabel11_x = new javax.swing.JLabel();
        exterior_x = new javax.swing.JPanel();
        base_7_x = new javax.swing.JPanel();
        Close3 = new javax.swing.JLabel();
        Minimize3 = new javax.swing.JLabel();
        jLabel12_x = new javax.swing.JLabel();
        jLabel13_x = new javax.swing.JLabel();
        specs_x = new javax.swing.JPanel();
        base_8 = new javax.swing.JPanel();
        Close2 = new javax.swing.JLabel();
        Minimize2 = new javax.swing.JLabel();
        jLabel14_x = new javax.swing.JLabel();
        jLabel15_x = new javax.swing.JLabel();
        order_x = new javax.swing.JPanel();
        base_9_x = new javax.swing.JPanel();
        Close1 = new javax.swing.JLabel();
        Minimize1 = new javax.swing.JLabel();
        jLabel16_x = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17_x = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub_x.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sub_xMouseDragged(evt);
            }
        });
        sub_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sub_xMousePressed(evt);
            }
        });
        sub_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Base_X.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
        });
        Base_X.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizeMousePressed(evt);
            }
        });
        Base_X.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel2_x.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2_x.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_x.setText("                                     Safety");
        jLabel2_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2_xMousePressed(evt);
            }
        });
        Base_X.add(jLabel2_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 670, 190, 50));

        Background_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Videos/Model_x/Home_hero.gif"))); // NOI18N
        Base_X.add(Background_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout model_home_XLayout = new javax.swing.GroupLayout(model_home_X);
        model_home_X.setLayout(model_home_XLayout);
        model_home_XLayout.setHorizontalGroup(
            model_home_XLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base_X, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        model_home_XLayout.setVerticalGroup(
            model_home_XLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base_X, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_x.add(model_home_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        safety_X.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Base_2_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close8MousePressed(evt);
            }
        });
        Base_2_x.add(Close8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize8MousePressed(evt);
            }
        });
        Base_2_x.add(Minimize8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel3_x.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel3_x.setText("       Utility");
        jLabel3_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3_xMousePressed(evt);
            }
        });
        Base_2_x.add(jLabel3_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, 190, 50));

        safe_pan_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Videos/Model_x/Safety.gif"))); // NOI18N
        Base_2_x.add(safe_pan_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        safety_X.add(Base_2_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        main_x.add(safety_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        range_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_4_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close6MousePressed(evt);
            }
        });
        base_4_x.add(Close6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize6MousePressed(evt);
            }
        });
        base_4_x.add(Minimize6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel6_x.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel6_x.setText("  Autopilot");
        jLabel6_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6_xMousePressed(evt);
            }
        });
        base_4_x.add(jLabel6_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel7_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Videos/Model_x/Range.gif"))); // NOI18N
        base_4_x.add(jLabel7_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        range_x.add(base_4_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_x.add(range_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        autopilot_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_5_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close5MousePressed(evt);
            }
        });
        base_5_x.add(Close5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize5MousePressed(evt);
            }
        });
        base_5_x.add(Minimize5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel8_x.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel8_x.setText("  Interior");
        jLabel8_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8_xMousePressed(evt);
            }
        });
        base_5_x.add(jLabel8_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel9_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Videos/Model_x/autopilot.gif"))); // NOI18N
        base_5_x.add(jLabel9_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        autopilot_x.add(base_5_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_x.add(autopilot_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        performance_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_3_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close7MousePressed(evt);
            }
        });
        base_3_x.add(Close7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize7MousePressed(evt);
            }
        });
        base_3_x.add(Minimize7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel5_x.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel5_x.setText("   Range");
        jLabel5_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5_xMousePressed(evt);
            }
        });
        base_3_x.add(jLabel5_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 80, 50));

        jLabel4_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Videos/Model_x/performance.gif"))); // NOI18N
        base_3_x.add(jLabel4_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        performance_x.add(base_3_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_x.add(performance_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        interior_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_6_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close4MousePressed(evt);
            }
        });
        base_6_x.add(Close4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize4MousePressed(evt);
            }
        });
        base_6_x.add(Minimize4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel10_x.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel10_x.setText("  Exterior");
        jLabel10_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10_xMousePressed(evt);
            }
        });
        base_6_x.add(jLabel10_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel11_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Videos/Model_x/Interior.gif"))); // NOI18N
        base_6_x.add(jLabel11_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        interior_x.add(base_6_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_x.add(interior_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        exterior_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_7_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close3MousePressed(evt);
            }
        });
        base_7_x.add(Close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize3MousePressed(evt);
            }
        });
        base_7_x.add(Minimize3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel12_x.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel12_x.setText(" Specs");
        jLabel12_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12_xMousePressed(evt);
            }
        });
        base_7_x.add(jLabel12_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel13_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Videos/Model_x/Exterior.gif"))); // NOI18N
        base_7_x.add(jLabel13_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        exterior_x.add(base_7_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_x.add(exterior_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        specs_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close2MousePressed(evt);
            }
        });
        base_8.add(Close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize2MousePressed(evt);
            }
        });
        base_8.add(Minimize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel14_x.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14_x.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate-www.png"))); // NOI18N
        jLabel14_x.setText("  Overview");
        jLabel14_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14_xMousePressed(evt);
            }
        });
        base_8.add(jLabel14_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel15_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Videos/Model_x/specs.gif"))); // NOI18N
        base_8.add(jLabel15_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        specs_x.add(base_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_x.add(specs_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        order_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_9_x.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close1MousePressed(evt);
            }
        });
        base_9_x.add(Close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize1MousePressed(evt);
            }
        });
        base_9_x.add(Minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel16_x.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-up-sign-to-navigate.png"))); // NOI18N
        jLabel16_x.setText(" Back to Home");
        jLabel16_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16_xMousePressed(evt);
            }
        });
        base_9_x.add(jLabel16_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        base_9_x.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 110, 30));

        jLabel17_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Videos/Model_x/Order Now.gif"))); // NOI18N
        base_9_x.add(jLabel17_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        order_x.add(base_9_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_x.add(order_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
        order_x.getAccessibleContext().setAccessibleDescription("");

        sub_x.add(main_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(sub_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CloseMousePressed

    private void MinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMousePressed

    private void jLabel2_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_xMousePressed
        //  set active to Safety
        active="Safety";
        try{
            main_x.removeAll();
            main_x.repaint();
            main_x.revalidate();
            //adding the target pannel
            main_x.add(safety_X);
            main_x.repaint();
            main_x.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_jLabel2_xMousePressed

    private void Close8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close8MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close8MousePressed

    private void Minimize8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize8MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize8MousePressed

    private void jLabel3_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_xMousePressed
        // set active to Performance
        active="Performance";
        try{
            main_x.removeAll();
            main_x.repaint();
            main_x.revalidate();
            //adding the target pannel
            main_x.add(performance_x);
            main_x.repaint();
            main_x.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_jLabel3_xMousePressed

    private void Close7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close7MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close7MousePressed

    private void Minimize7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize7MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize7MousePressed

    private void jLabel5_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5_xMousePressed
        // active="range";
        try{
            main_x.removeAll();
            main_x.repaint();
            main_x.revalidate();
            //adding the target pannel
            main_x.add(range_x);
            main_x.repaint();
            main_x.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_jLabel5_xMousePressed

    private void Close6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close6MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close6MousePressed

    private void Minimize6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize6MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize6MousePressed

    private void jLabel6_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6_xMousePressed
        //  set active to autopilot
        active="autopilot";
        try{
            main_x.removeAll();
            main_x.repaint();
            main_x.revalidate();
            //adding the target pannel
            main_x.add(autopilot_x);
            main_x.repaint();
            main_x.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_jLabel6_xMousePressed

    private void Close5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close5MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close5MousePressed

    private void Minimize5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize5MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize5MousePressed

    private void jLabel8_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8_xMousePressed
        // set active to interior
        active="interior";
        try{
            main_x.removeAll();
            main_x.repaint();
            main_x.revalidate();
            //adding the target pannel
            main_x.add(interior_x);
            main_x.repaint();
            main_x.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_jLabel8_xMousePressed

    private void Close4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close4MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close4MousePressed

    private void Minimize4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize4MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize4MousePressed

    private void jLabel10_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10_xMousePressed
        // set active to interior
        active="interior";
        try{
            main_x.removeAll();
            main_x.repaint();
            main_x.revalidate();
            //adding the target pannel
            main_x.add(exterior_x);
            main_x.repaint();
            main_x.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_jLabel10_xMousePressed

    private void Close3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close3MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close3MousePressed

    private void Minimize3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize3MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize3MousePressed

    private void jLabel12_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12_xMousePressed
        // set active to specs
        active="specs";
        try{
            main_x.removeAll();
            main_x.repaint();
            main_x.revalidate();
            //adding the target pannel
            main_x.add(specs_x);
            main_x.repaint();
            main_x.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_jLabel12_xMousePressed

    private void Close2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close2MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close2MousePressed

    private void Minimize2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize2MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize2MousePressed

    private void jLabel14_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14_xMousePressed
        // set active to Overview
        active="order now";
        try{
            main_x.removeAll();
            main_x.repaint();
            main_x.revalidate();
            //adding the target pannel
            main_x.add(order_x);
            main_x.repaint();
            main_x.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_jLabel14_xMousePressed

    private void Close1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close1MousePressed

    private void Minimize1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize1MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize1MousePressed

    private void jLabel16_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16_xMousePressed
        // set active to Home
        active="Home";
        try{
            main_x.removeAll();
            main_x.repaint();
            main_x.revalidate();
            //adding the target pannel
            main_x.add(model_home_X);
            main_x.repaint();
            main_x.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_jLabel16_xMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Window Opener:
        try{
                    main_x.removeAll();
                    main_x.repaint();
                    main_x.revalidate();

                    main_x.add(model_home_X);
                    main_x.repaint();
                    main_x.revalidate();
               }catch(Exception e){
                 
               }
    }//GEN-LAST:event_formWindowOpened

    private void sub_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub_xMousePressed
        // Press Drag:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_sub_xMousePressed

    private void sub_xMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub_xMouseDragged
        // Drag:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_sub_xMouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // Order:
        Order_X ox=new Order_X();
        ox.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Model_X.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Model_X.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Model_X.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Model_X.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Model_X().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background_x;
    private javax.swing.JPanel Base_2_x;
    private javax.swing.JPanel Base_X;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Close1;
    private javax.swing.JLabel Close2;
    private javax.swing.JLabel Close3;
    private javax.swing.JLabel Close4;
    private javax.swing.JLabel Close5;
    private javax.swing.JLabel Close6;
    private javax.swing.JLabel Close7;
    private javax.swing.JLabel Close8;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Minimize1;
    private javax.swing.JLabel Minimize2;
    private javax.swing.JLabel Minimize3;
    private javax.swing.JLabel Minimize4;
    private javax.swing.JLabel Minimize5;
    private javax.swing.JLabel Minimize6;
    private javax.swing.JLabel Minimize7;
    private javax.swing.JLabel Minimize8;
    private javax.swing.JPanel autopilot_x;
    private javax.swing.JPanel base_3_x;
    private javax.swing.JPanel base_4_x;
    private javax.swing.JPanel base_5_x;
    private javax.swing.JPanel base_6_x;
    private javax.swing.JPanel base_7_x;
    private javax.swing.JPanel base_8;
    private javax.swing.JPanel base_9_x;
    private javax.swing.JPanel exterior_x;
    private javax.swing.JPanel interior_x;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10_x;
    private javax.swing.JLabel jLabel11_x;
    private javax.swing.JLabel jLabel12_x;
    private javax.swing.JLabel jLabel13_x;
    private javax.swing.JLabel jLabel14_x;
    private javax.swing.JLabel jLabel15_x;
    private javax.swing.JLabel jLabel16_x;
    private javax.swing.JLabel jLabel17_x;
    private javax.swing.JLabel jLabel2_x;
    private javax.swing.JLabel jLabel3_x;
    private javax.swing.JLabel jLabel4_x;
    private javax.swing.JLabel jLabel5_x;
    private javax.swing.JLabel jLabel6_x;
    private javax.swing.JLabel jLabel7_x;
    private javax.swing.JLabel jLabel8_x;
    private javax.swing.JLabel jLabel9_x;
    private javax.swing.JPanel main_x;
    private javax.swing.JPanel model_home_X;
    private javax.swing.JPanel order_x;
    private javax.swing.JPanel performance_x;
    private javax.swing.JPanel range_x;
    private javax.swing.JLabel safe_pan_x;
    private javax.swing.JPanel safety_X;
    private javax.swing.JPanel specs_x;
    private javax.swing.JPanel sub_x;
    // End of variables declaration//GEN-END:variables
}
