import Main.Profiles;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mahi
 */
public class Create_New extends javax.swing.JFrame {

    /**
     * Creates new form Create_New
     */
    public Create_New() {
        initComponents();
        ImageIcon ic = new ImageIcon(getClass().getResource("/Icons/Tesla_Logo.png"));
        this.setIconImage(ic.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PF = new javax.swing.JPasswordField();
        Create = new javax.swing.JLabel();
        USF = new javax.swing.JTextField();
        EAF = new javax.swing.JTextField();
        LNF = new javax.swing.JTextField();
        FNF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Signin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 0, 110, 40));

        PF.setText("jPasswordField1");
        PF.setBorder(null);
        PF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PFFocusLost(evt);
            }
        });
        getContentPane().add(PF, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 640, 570, 20));

        Create.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Create.setForeground(new java.awt.Color(255, 255, 255));
        Create.setText("                                                                        CREATE ACCOUNT");
        Create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateMouseClicked(evt);
            }
        });
        getContentPane().add(Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 850, 710, 40));

        USF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        USF.setText("User Name");
        USF.setBorder(null);
        USF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                USFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                USFFocusLost(evt);
            }
        });
        getContentPane().add(USF, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 680, 20));

        EAF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EAF.setText("Email Address");
        EAF.setBorder(null);
        EAF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EAFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EAFFocusLost(evt);
            }
        });
        EAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EAFActionPerformed(evt);
            }
        });
        getContentPane().add(EAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 680, 20));

        LNF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LNF.setText("Last Name");
        LNF.setBorder(null);
        LNF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LNFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LNFFocusLost(evt);
            }
        });
        LNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNFActionPerformed(evt);
            }
        });
        getContentPane().add(LNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 680, 20));

        FNF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FNF.setText("First Name");
        FNF.setBorder(null);
        FNF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FNFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FNFFocusLost(evt);
            }
        });
        getContentPane().add(FNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, 680, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel5.setText("Create Account");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 360, 190, 30));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 700, 10));

        Signin.setBackground(new java.awt.Color(51, 153, 255));
        Signin.setText("                                                                                                       Already have an account? Sign In");
        Signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SigninMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SigninMousePressed(evt);
            }
        });
        getContentPane().add(Signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 770, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Image/Create.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 890, 730));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Image/login-semi-hangar Register New Account.jpg"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(1280, 720));
        Background.setMinimumSize(new java.awt.Dimension(1280, 720));
        Background.setPreferredSize(new java.awt.Dimension(1280, 720));
        Background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BackgroundMouseDragged(evt);
            }
        });
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackgroundMousePressed(evt);
            }
        });
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 2480, 1290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateMouseClicked
        // Create :
        String user = USF.getText();
        
        if(user.isEmpty()){
            USF.requestFocus();
            JOptionPane.showMessageDialog(null,"Enter Username");
        }
        
        String pass=new String(PF.getPassword());
        
        if(pass.isEmpty()){
        PF.requestFocus();
            JOptionPane.showMessageDialog(null,"Enter Password");
        }
        
        String First=new String(FNF.getText());
        
        if(pass.isEmpty()){
        FNF.requestFocus();
            JOptionPane.showMessageDialog(null,"Enter First Name");
        }
        
        String Last=new String(LNF.getText());
        
        if(pass.isEmpty()){
        LNF.requestFocus();
            JOptionPane.showMessageDialog(null,"Enter Last Name");
        }
        
        String EM=new String(EAF.getText());
        
        if(pass.isEmpty()){
        EAF.requestFocus();
            JOptionPane.showMessageDialog(null,"Enter Email");
        }
        
        else

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Tesla_Project","root","");
            Statement stmt =con.createStatement();
            String sq="INSERT INTO `adminportal`(`Username`, `Password`) VALUES("+user+","+pass+");";
            String sp="INSERT into Profile(First Name,Last Name,Email)values("+First+","+Last+","+EM+");";
            ResultSet rs=stmt.executeQuery(sq);
            ResultSet rp=stmt.executeQuery(sp);
           
            
            JOptionPane.showMessageDialog(null,"Registration Successfull");
            
            
                JOptionPane.showMessageDialog(null,"Successfully Logged in");
                Profiles pf=new Profiles();
                pf.setVisible(true);
                this.dispose();
            
            rs.close();
            rp.close();
            stmt.close();
            con.close();

        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_CreateMouseClicked

    private void FNFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FNFFocusGained
        //Focus Gain for First Name:
        if(FNF.getText().equals("First Name")){
            FNF.setText("");
        }
    }//GEN-LAST:event_FNFFocusGained

    private void FNFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FNFFocusLost
        // Focus Lost for First Name:
        if(FNF.getText().equals("")){
            FNF.setText("First Name");
        }
    }//GEN-LAST:event_FNFFocusLost

    private void LNFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LNFFocusGained
        // Focus Gain for Last Name:
        if(LNF.getText().equals("Last Name")){
            LNF.setText("");
        }
    }//GEN-LAST:event_LNFFocusGained

    private void LNFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LNFFocusLost
        // Focus Lost for Last Name:
        if(LNF.getText().equals("")){
            LNF.setText("Last Name");
        }
    }//GEN-LAST:event_LNFFocusLost

    private void EAFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EAFFocusGained
        // Focus Gain for Email Address:
        if(EAF.getText().equals("Email Address")){
            EAF.setText("");
        }
    }//GEN-LAST:event_EAFFocusGained

    private void EAFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EAFFocusLost
        //  Focus Lost for Email Address:
        if(EAF.getText().equals("")){
            EAF.setText("Email Address");
        }
    }//GEN-LAST:event_EAFFocusLost

    private void EAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EAFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EAFActionPerformed

    private void LNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNFActionPerformed

    private void SigninMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninMousePressed
        // 
    }//GEN-LAST:event_SigninMousePressed

    private void SigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninMouseClicked
        // Login:
        Login L = new Login();
        L.setVisible(true);
        dispose();
    }//GEN-LAST:event_SigninMouseClicked

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // Close:
        System.exit(0);
    }//GEN-LAST:event_jLabel7MousePressed
int x,y;
    private void BackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMousePressed
        //Press Drag:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_BackgroundMousePressed

    private void BackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseDragged
        // Drag:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_BackgroundMouseDragged

    private void USFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_USFFocusGained
        // Focus Gain for Password:
        if(USF.getText().equals("User Name")){
            USF.setText("");
        }
    }//GEN-LAST:event_USFFocusGained

    private void USFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_USFFocusLost
        // Focus Gain for Password:
        if(USF.getText().equals("")){
            USF.setText("User Name");
        }
    }//GEN-LAST:event_USFFocusLost

    private void PFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PFFocusGained
        // Focus Gain for Password:
        if(PF.getPassword().equals("Password")){
            PF.setText("");
        }
    }//GEN-LAST:event_PFFocusGained

    private void PFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PFFocusLost
        //  Focus Lost for Password:
        if(PF.getPassword().equals("")){
            PF.setText("Password");
        }
    }//GEN-LAST:event_PFFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_New().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Create;
    private javax.swing.JTextField EAF;
    private javax.swing.JTextField FNF;
    private javax.swing.JTextField LNF;
    private javax.swing.JPasswordField PF;
    private javax.swing.JLabel Signin;
    private javax.swing.JTextField USF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
