/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author mahen
 */
public class Dashboard_Home extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_Home
     */
    public Dashboard_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dash_home = new javax.swing.JPanel();
        Count_Dis = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Cars_Label = new javax.swing.JLabel();
        Count_Dis1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Ser_Label = new javax.swing.JLabel();
        Count_Dis2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        BK_Label = new javax.swing.JLabel();
        Count_Dis3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Del_Label = new javax.swing.JLabel();
        Count_Dis4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Emp_Label = new javax.swing.JLabel();
        Count_Dis5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Cus_Label = new javax.swing.JLabel();
        main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dash_home.setLayout(null);

        Count_Dis.setBackground(new java.awt.Color(95, 206, 155));
        Count_Dis.setPreferredSize(new java.awt.Dimension(153, 100));
        Count_Dis.setRequestFocusEnabled(false);
        Count_Dis.setLayout(null);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Car-X.png"))); // NOI18N
        Count_Dis.add(jLabel20);
        jLabel20.setBounds(47, 0, 59, 50);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("Cars");
        Count_Dis.add(jLabel23);
        jLabel23.setBounds(79, 68, 27, 15);

        Cars_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Count_Dis.add(Cars_Label);
        Cars_Label.setBounds(30, 60, 40, 30);

        dash_home.add(Count_Dis);
        Count_Dis.setBounds(21, 21, 153, 100);

        Count_Dis1.setBackground(new java.awt.Color(102, 181, 214));
        Count_Dis1.setPreferredSize(new java.awt.Dimension(153, 100));
        Count_Dis1.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setText("Services");
        Count_Dis1.add(jLabel24);
        jLabel24.setBounds(61, 64, 50, 15);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon.png"))); // NOI18N
        Count_Dis1.add(jLabel21);
        jLabel21.setBounds(61, 11, 59, 24);

        Ser_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Count_Dis1.add(Ser_Label);
        Ser_Label.setBounds(20, 60, 40, 30);

        dash_home.add(Count_Dis1);
        Count_Dis1.setBounds(195, 21, 153, 100);

        Count_Dis2.setBackground(new java.awt.Color(232, 115, 82));
        Count_Dis2.setPreferredSize(new java.awt.Dimension(153, 100));
        Count_Dis2.setLayout(null);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/check-mark.png"))); // NOI18N
        Count_Dis2.add(jLabel26);
        jLabel26.setBounds(60, 7, 59, 32);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setText("Bookings");
        Count_Dis2.add(jLabel25);
        jLabel25.setBounds(74, 66, 53, 15);

        BK_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Count_Dis2.add(BK_Label);
        BK_Label.setBounds(30, 60, 40, 30);

        dash_home.add(Count_Dis2);
        Count_Dis2.setBounds(369, 21, 153, 100);

        Count_Dis3.setBackground(new java.awt.Color(238, 202, 90));
        Count_Dis3.setPreferredSize(new java.awt.Dimension(153, 100));
        Count_Dis3.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("Delivered");
        Count_Dis3.add(jLabel28);
        jLabel28.setBounds(75, 65, 53, 15);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/key.png"))); // NOI18N
        Count_Dis3.add(jLabel27);
        jLabel27.setBounds(57, 7, 59, 32);

        Del_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Count_Dis3.add(Del_Label);
        Del_Label.setBounds(30, 60, 40, 30);

        dash_home.add(Count_Dis3);
        Count_Dis3.setBounds(543, 21, 153, 100);

        Count_Dis4.setBackground(new java.awt.Color(95, 206, 155));
        Count_Dis4.setPreferredSize(new java.awt.Dimension(153, 100));
        Count_Dis4.setLayout(null);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setText("Employees");
        Count_Dis4.add(jLabel29);
        jLabel29.setBounds(70, 60, 62, 15);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/network.png"))); // NOI18N
        Count_Dis4.add(jLabel30);
        jLabel30.setBounds(60, 5, 32, 39);

        Emp_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Count_Dis4.add(Emp_Label);
        Emp_Label.setBounds(30, 50, 40, 40);

        dash_home.add(Count_Dis4);
        Count_Dis4.setBounds(717, 21, 153, 100);

        Count_Dis5.setBackground(new java.awt.Color(102, 181, 214));
        Count_Dis5.setPreferredSize(new java.awt.Dimension(153, 100));
        Count_Dis5.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setText("Customers");
        Count_Dis5.add(jLabel31);
        jLabel31.setBounds(77, 65, 63, 15);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/manager.png"))); // NOI18N
        Count_Dis5.add(jLabel32);
        jLabel32.setBounds(64, 7, 59, 32);

        Cus_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Count_Dis5.add(Cus_Label);
        Cus_Label.setBounds(30, 60, 40, 30);

        dash_home.add(Count_Dis5);
        Count_Dis5.setBounds(891, 21, 153, 100);

        main.setLayout(null);
        dash_home.add(main);
        main.setBounds(0, 0, 1060, 840);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dash_home, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dash_home, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BK_Label;
    private javax.swing.JLabel Cars_Label;
    private javax.swing.JPanel Count_Dis;
    private javax.swing.JPanel Count_Dis1;
    private javax.swing.JPanel Count_Dis2;
    private javax.swing.JPanel Count_Dis3;
    private javax.swing.JPanel Count_Dis4;
    private javax.swing.JPanel Count_Dis5;
    private javax.swing.JLabel Cus_Label;
    private javax.swing.JLabel Del_Label;
    private javax.swing.JLabel Emp_Label;
    private javax.swing.JLabel Ser_Label;
    private javax.swing.JPanel dash_home;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
