import Main.Dashboard;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mahen
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Header.setBackground(new Color(51,51,51,85));
        ImageIcon ic = new ImageIcon(getClass().getResource("/Icons/Tesla_Logo.png"));
        this.setIconImage(ic.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PasswordF = new javax.swing.JPasswordField();
        UsernameF = new javax.swing.JTextField();
        Create_Acc = new javax.swing.JLabel();
        Login_Button = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        Login_Box = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 640));
        setSize(new java.awt.Dimension(720, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(51, 51, 51));
        Header.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");
        Header.add(jLabel3);
        jLabel3.setBounds(50, 10, 280, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user-Log.png"))); // NOI18N
        Header.add(jLabel5);
        jLabel5.setBounds(10, 0, 30, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        Header.add(jLabel2);
        jLabel2.setBounds(1800, 0, 40, 50);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        Header.add(jLabel1);
        jLabel1.setBounds(1850, 10, 40, 30);

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1900, 50));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 440, 20));

        PasswordF.setBackground(new java.awt.Color(229, 238, 252));
        PasswordF.setBorder(null);
        PasswordF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFFocusLost(evt);
            }
        });
        PasswordF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordF, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 430, 30));

        UsernameF.setBackground(new java.awt.Color(229, 238, 252));
        UsernameF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UsernameF.setText("  U s e r n a m e");
        UsernameF.setBorder(null);
        UsernameF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFFocusLost(evt);
            }
        });
        UsernameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 430, 30));

        Create_Acc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Create_Acc.setText("                                                                                      Create an Account");
        Create_Acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Create_AccMouseClicked(evt);
            }
        });
        getContentPane().add(Create_Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 600, 40));

        Login_Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Login_Button.setText("                                                                              Login");
        Login_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 500, 40));

        Login.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        Login.setText("Login");
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, -1, -1));

        Login_Box.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Image/Untitled-1.png"))); // NOI18N
        getContentPane().add(Login_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 720, 370));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Image/login-semi-interior-Login.jpg"))); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(1920, 480));
        Background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BackgroundMouseDragged(evt);
            }
        });
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackgroundMousePressed(evt);
            }
        });
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1980, 740));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1900, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFActionPerformed

    private void Login_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseClicked
        // Login:
        String user = UsernameF.getText();
        
        if(user.isEmpty()){
            UsernameF.requestFocus();
            JOptionPane.showMessageDialog(null,"Enter Username");
        }
        
        String pass=new String(PasswordF.getPassword());
        
        if(pass.isEmpty()){
        PasswordF.requestFocus();
            JOptionPane.showMessageDialog(null,"Enter Password");
        }
        else

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tesla_project","root","");
            Statement stmt =con.createStatement();
            String sq="SELECT Username,Password,Image FROM adminportal WHERE Username='"+user+"' AND Password='"+pass+"';";
            ResultSet rs=stmt.executeQuery(sq);
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Successfully Logged in");
                Dashboard.usernamelabel.setText(rs.getString("Username"));
                Dashboard db=new Dashboard();
                db.setVisible(true);
                this.dispose();}
            else
            {
                jLabel4.setText("Invalid username and Password. Please re-enter");
                
                UsernameF.setText("");
                PasswordF.setText("");
                UsernameF.requestFocus();
            }
            rs.close();
            stmt.close();
            con.close();

        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_Login_ButtonMouseClicked

    private void Create_AccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Create_AccMouseClicked
        // Create New:
        Create_New cn = new Create_New();
        cn.setVisible(true);
        dispose();
    }//GEN-LAST:event_Create_AccMouseClicked

    private void UsernameFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFFocusGained
        // Focus Gain
        if(UsernameF.getText().equals("  U s e r n a m e")){
            UsernameF.setText("");
        }
    }//GEN-LAST:event_UsernameFFocusGained

    private void UsernameFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFFocusLost
        // Focus Lost
        if(UsernameF.getText().equals("")){
            UsernameF.setText("  U s e r n a m e");
        }  
    }//GEN-LAST:event_UsernameFFocusLost

    private void PasswordFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFActionPerformed

    private void PasswordFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFFocusGained
        // Pass Focus Gain:
        if(PasswordF.getPassword().equals("Password")){
            PasswordF.setText("");
        }
    }//GEN-LAST:event_PasswordFFocusGained

    private void PasswordFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFFocusLost
        // Pass Focus Lost:
        if(PasswordF.getPassword().equals("")){
            PasswordF.setText("Password");
        }
    }//GEN-LAST:event_PasswordFFocusLost

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // Close:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MousePressed

    private void BackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseDragged
        // Drag:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_BackgroundMouseDragged
int x,y;
    private void BackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMousePressed
        // Press Drag:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_BackgroundMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Create_Acc;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Login_Box;
    private javax.swing.JLabel Login_Button;
    private javax.swing.JPasswordField PasswordF;
    private javax.swing.JTextField UsernameF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
