/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author mahen
 */
public class Model_S extends javax.swing.JFrame {

    /**
     * Creates new form Model_S
     */
    public Model_S() {
        initComponents();
        ImageIcon ic = new ImageIcon(getClass().getResource("/Icons/Tesla_Logo.png"));
        this.setIconImage(ic.getImage());
    }
    String active ="Safety";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sub = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        model_home = new javax.swing.JPanel();
        Base = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        safety = new javax.swing.JPanel();
        Base_2 = new javax.swing.JPanel();
        Close8 = new javax.swing.JLabel();
        Minimize8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        safe_pan = new javax.swing.JLabel();
        performance = new javax.swing.JPanel();
        base_3 = new javax.swing.JPanel();
        Close7 = new javax.swing.JLabel();
        Minimize7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        range = new javax.swing.JPanel();
        base_4 = new javax.swing.JPanel();
        Close6 = new javax.swing.JLabel();
        Minimize6 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        autopilot = new javax.swing.JPanel();
        base_5 = new javax.swing.JPanel();
        Close5 = new javax.swing.JLabel();
        Minimize5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        interior = new javax.swing.JPanel();
        base_6 = new javax.swing.JPanel();
        Close4 = new javax.swing.JLabel();
        Minimize4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        exterior = new javax.swing.JPanel();
        base_7 = new javax.swing.JPanel();
        Close3 = new javax.swing.JLabel();
        Minimize3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        specs = new javax.swing.JPanel();
        base_8 = new javax.swing.JPanel();
        Close2 = new javax.swing.JLabel();
        Minimize2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        order = new javax.swing.JPanel();
        base_9 = new javax.swing.JPanel();
        Close1 = new javax.swing.JLabel();
        Minimize1 = new javax.swing.JLabel();
        Order_Now = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel1.setText("Safety");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                subMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                subMouseMoved(evt);
            }
        });
        sub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subMousePressed(evt);
            }
        });
        sub.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
        });
        Base.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizeMousePressed(evt);
            }
        });
        Base.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("                                     Safety");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        Base.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 670, 190, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model_S/Model S Intro 1.gif"))); // NOI18N
        Base.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout model_homeLayout = new javax.swing.GroupLayout(model_home);
        model_home.setLayout(model_homeLayout);
        model_homeLayout.setHorizontalGroup(
            model_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        model_homeLayout.setVerticalGroup(
            model_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main.add(model_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        safety.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Base_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close8MousePressed(evt);
            }
        });
        Base_2.add(Close8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize8MousePressed(evt);
            }
        });
        Base_2.add(Minimize8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel3.setText("       Performance");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        Base_2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, 190, 50));

        safe_pan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Safety.gif"))); // NOI18N
        Base_2.add(safe_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        safety.add(Base_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        main.add(safety, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        performance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close7MousePressed(evt);
            }
        });
        base_3.add(Close7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize7MousePressed(evt);
            }
        });
        base_3.add(Minimize7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel5.setText("   Range");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        base_3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 80, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Perfomance.gif"))); // NOI18N
        base_3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        performance.add(base_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main.add(performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        range.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close6MousePressed(evt);
            }
        });
        base_4.add(Close6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize6MousePressed(evt);
            }
        });
        base_4.add(Minimize6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel6.setText("   Autopilot");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        base_4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Range.gif"))); // NOI18N
        base_4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        range.add(base_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main.add(range, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        autopilot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close5MousePressed(evt);
            }
        });
        base_5.add(Close5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize5MousePressed(evt);
            }
        });
        base_5.add(Minimize5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel8.setText("  Interior");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        base_5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Autonomous.gif"))); // NOI18N
        base_5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        autopilot.add(base_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main.add(autopilot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        interior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close4MousePressed(evt);
            }
        });
        base_6.add(Close4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize4MousePressed(evt);
            }
        });
        base_6.add(Minimize4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel10.setText("  Exterior");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        base_6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Interior.gif"))); // NOI18N
        base_6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        interior.add(base_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main.add(interior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        exterior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close3MousePressed(evt);
            }
        });
        base_7.add(Close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize3MousePressed(evt);
            }
        });
        base_7.add(Minimize3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate.png"))); // NOI18N
        jLabel12.setText(" Specs");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        base_7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Exterior.gif"))); // NOI18N
        base_7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        exterior.add(base_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main.add(exterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        specs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close2MousePressed(evt);
            }
        });
        base_8.add(Close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize2MousePressed(evt);
            }
        });
        base_8.add(Minimize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-down-sign-to-navigate-www.png"))); // NOI18N
        jLabel14.setText("  Overview");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        base_8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Specs.gif"))); // NOI18N
        base_8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        specs.add(base_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main.add(specs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        order.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close1MousePressed(evt);
            }
        });
        base_9.add(Close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize1MousePressed(evt);
            }
        });
        base_9.add(Minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        Order_Now.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Order_Now.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Order_NowMousePressed(evt);
            }
        });
        base_9.add(Order_Now, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 120, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-up-sign-to-navigate.png"))); // NOI18N
        jLabel16.setText(" Back to Home");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });
        base_9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 110, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Order Now.gif"))); // NOI18N
        base_9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        order.add(base_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        sub.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CloseMousePressed

    private void MinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        //
    }//GEN-LAST:event_jLabel1MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Window Opener:
        try{
                    main.removeAll();
                    main.repaint();
                    main.revalidate();

                    main.add(model_home);
                    main.repaint();
                    main.revalidate();
               }catch(Exception e){
                 
               }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        //  set active to Safety
        active="Safety";      
        try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(safety);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // set active to Performance
        active="Performance";      
        try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(performance);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // active="range";      
        try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(range);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        //  set active to autopilot
        active="autopilot";      
        try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(autopilot);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // set active to interior
        active="interior";      
        try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(interior);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // set active to interior
        active="interior";      
        try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(exterior);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // set active to specs
        active="specs";      
        try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(specs);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        // set active to Overview
        active="order now";      
        try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(order);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_jLabel14MousePressed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        // set active to Home
        active="Home";      
        try{ 
                    main.removeAll();
                    main.repaint();
                    main.revalidate();
                    //adding the target pannel
                    main.add(model_home);
                    main.repaint();
                    main.revalidate();
                }catch(Exception e){
                 
               }
    }//GEN-LAST:event_jLabel16MousePressed

    private void Close1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close1MousePressed

    private void Minimize1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize1MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize1MousePressed

    private void Close2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close2MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close2MousePressed

    private void Minimize2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize2MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize2MousePressed

    private void Close3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close3MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close3MousePressed

    private void Minimize3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize3MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize3MousePressed

    private void Close4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close4MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close4MousePressed

    private void Minimize4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize4MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize4MousePressed

    private void Close5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close5MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close5MousePressed

    private void Minimize5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize5MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize5MousePressed

    private void Close6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close6MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close6MousePressed

    private void Minimize6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize6MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize6MousePressed

    private void Close7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close7MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close7MousePressed

    private void Minimize7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize7MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize7MousePressed

    private void Close8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close8MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close8MousePressed

    private void Minimize8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize8MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize8MousePressed

    private void subMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMouseDragged
        // Drag:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_subMouseDragged

    private void subMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_subMouseMoved

    private void subMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMousePressed
        // Press Drag:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_subMousePressed

    private void Order_NowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Order_NowMousePressed
        // Order:
        Order_S os=new Order_S();
        os.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Order_NowMousePressed
int x,y;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Model_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Model_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Model_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Model_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Model_S().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Base;
    private javax.swing.JPanel Base_2;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Close1;
    private javax.swing.JLabel Close2;
    private javax.swing.JLabel Close3;
    private javax.swing.JLabel Close4;
    private javax.swing.JLabel Close5;
    private javax.swing.JLabel Close6;
    private javax.swing.JLabel Close7;
    private javax.swing.JLabel Close8;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Minimize1;
    private javax.swing.JLabel Minimize2;
    private javax.swing.JLabel Minimize3;
    private javax.swing.JLabel Minimize4;
    private javax.swing.JLabel Minimize5;
    private javax.swing.JLabel Minimize6;
    private javax.swing.JLabel Minimize7;
    private javax.swing.JLabel Minimize8;
    private javax.swing.JLabel Order_Now;
    private javax.swing.JPanel autopilot;
    private javax.swing.JPanel base_3;
    private javax.swing.JPanel base_4;
    private javax.swing.JPanel base_5;
    private javax.swing.JPanel base_6;
    private javax.swing.JPanel base_7;
    private javax.swing.JPanel base_8;
    private javax.swing.JPanel base_9;
    private javax.swing.JPanel exterior;
    private javax.swing.JPanel interior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel main;
    private javax.swing.JPanel model_home;
    private javax.swing.JPanel order;
    private javax.swing.JPanel performance;
    private javax.swing.JPanel range;
    private javax.swing.JLabel safe_pan;
    private javax.swing.JPanel safety;
    private javax.swing.JPanel specs;
    private javax.swing.JPanel sub;
    // End of variables declaration//GEN-END:variables
}
