/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import Main.Dashboard;
import javax.swing.ImageIcon;

/**
 *
 * @author mahen
 */
public class Order_S extends javax.swing.JFrame {

    /**
     * Creates new form Order_S
     */
    public Order_S() {
        initComponents();
        ImageIcon ic = new ImageIcon(getClass().getResource("/Icons/Tesla_Logo.png"));
        this.setIconImage(ic.getImage());
        this.setLocationRelativeTo(null);
    }
int x,y;
String active;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Order_Platform = new javax.swing.JPanel();
        main_order = new javax.swing.JPanel();
        Long = new javax.swing.JPanel();
        Base_L = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        pf = new javax.swing.JLabel();
        nxi1 = new javax.swing.JLabel();
        Background_L = new javax.swing.JLabel();
        Performance = new javax.swing.JPanel();
        Base_P = new javax.swing.JPanel();
        Close8 = new javax.swing.JLabel();
        Minimize8 = new javax.swing.JLabel();
        lg = new javax.swing.JLabel();
        nxi = new javax.swing.JLabel();
        Back_P = new javax.swing.JLabel();
        White = new javax.swing.JPanel();
        colour_w = new javax.swing.JPanel();
        Close6 = new javax.swing.JLabel();
        Minimize6 = new javax.swing.JLabel();
        nxe = new javax.swing.JLabel();
        rs = new javax.swing.JLabel();
        db = new javax.swing.JLabel();
        ms = new javax.swing.JLabel();
        bsm = new javax.swing.JLabel();
        ws = new javax.swing.JLabel();
        Back_W = new javax.swing.JLabel();
        Solid_Black = new javax.swing.JPanel();
        colour_black = new javax.swing.JPanel();
        Close5 = new javax.swing.JLabel();
        Minimize5 = new javax.swing.JLabel();
        nxe1 = new javax.swing.JLabel();
        rs4 = new javax.swing.JLabel();
        db4 = new javax.swing.JLabel();
        ms4 = new javax.swing.JLabel();
        bsm4 = new javax.swing.JLabel();
        ws4 = new javax.swing.JLabel();
        Back_Black = new javax.swing.JLabel();
        Midnight_Silver = new javax.swing.JPanel();
        colour_midnight = new javax.swing.JPanel();
        Close7 = new javax.swing.JLabel();
        Minimize7 = new javax.swing.JLabel();
        nxe2 = new javax.swing.JLabel();
        rs5 = new javax.swing.JLabel();
        db5 = new javax.swing.JLabel();
        ms5 = new javax.swing.JLabel();
        bsm5 = new javax.swing.JLabel();
        ws5 = new javax.swing.JLabel();
        Back_MS = new javax.swing.JLabel();
        Blue = new javax.swing.JPanel();
        colour_blue = new javax.swing.JPanel();
        Close3 = new javax.swing.JLabel();
        Minimize3 = new javax.swing.JLabel();
        nxe3 = new javax.swing.JLabel();
        rs6 = new javax.swing.JLabel();
        db6 = new javax.swing.JLabel();
        ms6 = new javax.swing.JLabel();
        bsm6 = new javax.swing.JLabel();
        ws6 = new javax.swing.JLabel();
        Back_Blue = new javax.swing.JLabel();
        Red = new javax.swing.JPanel();
        colour_red = new javax.swing.JPanel();
        Close2 = new javax.swing.JLabel();
        Minimize2 = new javax.swing.JLabel();
        nxe4 = new javax.swing.JLabel();
        rs7 = new javax.swing.JLabel();
        db7 = new javax.swing.JLabel();
        ms7 = new javax.swing.JLabel();
        bsm7 = new javax.swing.JLabel();
        ws7 = new javax.swing.JLabel();
        Back_red = new javax.swing.JLabel();
        Interior_A = new javax.swing.JPanel();
        Ash = new javax.swing.JPanel();
        Close1 = new javax.swing.JLabel();
        Minimize1 = new javax.swing.JLabel();
        nxe5 = new javax.swing.JLabel();
        cma = new javax.swing.JLabel();
        bwa = new javax.swing.JLabel();
        asa = new javax.swing.JLabel();
        ash_wood = new javax.swing.JLabel();
        Interior_WB = new javax.swing.JPanel();
        wb = new javax.swing.JPanel();
        Close4 = new javax.swing.JLabel();
        Minimize4 = new javax.swing.JLabel();
        nxe6 = new javax.swing.JLabel();
        cma1 = new javax.swing.JLabel();
        bwa1 = new javax.swing.JLabel();
        asa1 = new javax.swing.JLabel();
        wnb = new javax.swing.JLabel();
        Interior_C = new javax.swing.JPanel();
        cream = new javax.swing.JPanel();
        Close9 = new javax.swing.JLabel();
        Minimize9 = new javax.swing.JLabel();
        nxe7 = new javax.swing.JLabel();
        cma2 = new javax.swing.JLabel();
        bwa2 = new javax.swing.JLabel();
        asa2 = new javax.swing.JLabel();
        back_cream = new javax.swing.JLabel();
        Autopilot = new javax.swing.JPanel();
        Base_Auto = new javax.swing.JPanel();
        Close10 = new javax.swing.JLabel();
        Minimize10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        nxp = new javax.swing.JLabel();
        Background_Auto = new javax.swing.JLabel();
        Payment = new javax.swing.JPanel();
        pay = new javax.swing.JPanel();
        Close11 = new javax.swing.JLabel();
        Minimize11 = new javax.swing.JLabel();
        nxpay = new javax.swing.JLabel();
        Background_P = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Order_Platform.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Order_PlatformMouseDragged(evt);
            }
        });
        Order_Platform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Order_PlatformMousePressed(evt);
            }
        });
        Order_Platform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_order.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Base_L.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
        });
        Base_L.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizeMousePressed(evt);
            }
        });
        Base_L.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        pf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pfMousePressed(evt);
            }
        });
        Base_L.add(pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, 200, 30));

        nxi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxi1MousePressed(evt);
            }
        });
        Base_L.add(nxi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        Background_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/Long_Range_1.png"))); // NOI18N
        Base_L.add(Background_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout LongLayout = new javax.swing.GroupLayout(Long);
        Long.setLayout(LongLayout);
        LongLayout.setHorizontalGroup(
            LongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LongLayout.setVerticalGroup(
            LongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_order.add(Long, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Performance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Base_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close8MousePressed(evt);
            }
        });
        Base_P.add(Close8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize8MousePressed(evt);
            }
        });
        Base_P.add(Minimize8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        lg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lgMousePressed(evt);
            }
        });
        Base_P.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, 210, 30));

        nxi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxiMousePressed(evt);
            }
        });
        Base_P.add(nxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        Back_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/Performance_2.png"))); // NOI18N
        Base_P.add(Back_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Performance.add(Base_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        main_order.add(Performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        White.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colour_w.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close6MousePressed(evt);
            }
        });
        colour_w.add(Close6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize6MousePressed(evt);
            }
        });
        colour_w.add(Minimize6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        nxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxeMousePressed(evt);
            }
        });
        colour_w.add(nxe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        rs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rsMousePressed(evt);
            }
        });
        colour_w.add(rs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 320, 40, 40));

        db.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dbMousePressed(evt);
            }
        });
        colour_w.add(db, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 320, 30, 40));

        ms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                msMousePressed(evt);
            }
        });
        colour_w.add(ms, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, 30, 40));

        bsm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bsmMousePressed(evt);
            }
        });
        colour_w.add(bsm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 320, 30, 40));

        ws.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                wsMousePressed(evt);
            }
        });
        colour_w.add(ws, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 40, 40));

        Back_W.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/White.png"))); // NOI18N
        colour_w.add(Back_W, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        White.add(colour_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_order.add(White, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Solid_Black.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colour_black.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close5MousePressed(evt);
            }
        });
        colour_black.add(Close5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize5MousePressed(evt);
            }
        });
        colour_black.add(Minimize5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        nxe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxe1MousePressed(evt);
            }
        });
        colour_black.add(nxe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        rs4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rs4MousePressed(evt);
            }
        });
        colour_black.add(rs4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 320, 40, 40));

        db4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                db4MousePressed(evt);
            }
        });
        colour_black.add(db4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 320, 30, 40));

        ms4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ms4MousePressed(evt);
            }
        });
        colour_black.add(ms4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, 30, 40));

        bsm4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bsm4MousePressed(evt);
            }
        });
        colour_black.add(bsm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 320, 30, 40));

        ws4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ws4MousePressed(evt);
            }
        });
        colour_black.add(ws4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 40, 40));

        Back_Black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/Solid_Black.png"))); // NOI18N
        colour_black.add(Back_Black, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Solid_Black.add(colour_black, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_order.add(Solid_Black, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Midnight_Silver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colour_midnight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close7MousePressed(evt);
            }
        });
        colour_midnight.add(Close7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize7MousePressed(evt);
            }
        });
        colour_midnight.add(Minimize7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        nxe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxe2MousePressed(evt);
            }
        });
        colour_midnight.add(nxe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        rs5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rs5MousePressed(evt);
            }
        });
        colour_midnight.add(rs5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 320, 40, 40));

        db5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                db5MousePressed(evt);
            }
        });
        colour_midnight.add(db5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 320, 30, 40));

        ms5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ms5MousePressed(evt);
            }
        });
        colour_midnight.add(ms5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, 30, 40));

        bsm5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bsm5MousePressed(evt);
            }
        });
        colour_midnight.add(bsm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 320, 30, 40));

        ws5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ws5MousePressed(evt);
            }
        });
        colour_midnight.add(ws5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 40, 40));

        Back_MS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/Silver.png"))); // NOI18N
        colour_midnight.add(Back_MS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Midnight_Silver.add(colour_midnight, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_order.add(Midnight_Silver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Blue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colour_blue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close3MousePressed(evt);
            }
        });
        colour_blue.add(Close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize3MousePressed(evt);
            }
        });
        colour_blue.add(Minimize3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        nxe3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxe3MousePressed(evt);
            }
        });
        colour_blue.add(nxe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        rs6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rs6MousePressed(evt);
            }
        });
        colour_blue.add(rs6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 320, 40, 40));

        db6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                db6MousePressed(evt);
            }
        });
        colour_blue.add(db6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 320, 30, 40));

        ms6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ms6MousePressed(evt);
            }
        });
        colour_blue.add(ms6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, 30, 40));

        bsm6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bsm6MousePressed(evt);
            }
        });
        colour_blue.add(bsm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 320, 30, 40));

        ws6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ws6MousePressed(evt);
            }
        });
        colour_blue.add(ws6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 40, 40));

        Back_Blue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/Deep_Bluse.png"))); // NOI18N
        colour_blue.add(Back_Blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Blue.add(colour_blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_order.add(Blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Red.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colour_red.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close2MousePressed(evt);
            }
        });
        colour_red.add(Close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize2MousePressed(evt);
            }
        });
        colour_red.add(Minimize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        nxe4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxe4MousePressed(evt);
            }
        });
        colour_red.add(nxe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        rs7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rs7MousePressed(evt);
            }
        });
        colour_red.add(rs7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 320, 40, 40));

        db7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                db7MousePressed(evt);
            }
        });
        colour_red.add(db7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 320, 30, 40));

        ms7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ms7MousePressed(evt);
            }
        });
        colour_red.add(ms7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, 30, 40));

        bsm7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bsm7MousePressed(evt);
            }
        });
        colour_red.add(bsm7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 320, 30, 40));

        ws7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ws7MousePressed(evt);
            }
        });
        colour_red.add(ws7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 40, 40));

        Back_red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/Red.png"))); // NOI18N
        colour_red.add(Back_red, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Red.add(colour_red, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_order.add(Red, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Interior_A.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close1MousePressed(evt);
            }
        });
        Ash.add(Close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize1MousePressed(evt);
            }
        });
        Ash.add(Minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        nxe5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxe5MousePressed(evt);
            }
        });
        Ash.add(nxe5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        cma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmaMousePressed(evt);
            }
        });
        Ash.add(cma, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 80, 30, 30));

        bwa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bwaMousePressed(evt);
            }
        });
        Ash.add(bwa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 80, 30, 30));

        asa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asaMousePressed(evt);
            }
        });
        Ash.add(asa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 40, 30));

        ash_wood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/Ash.png"))); // NOI18N
        Ash.add(ash_wood, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Interior_A.add(Ash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_order.add(Interior_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Interior_WB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close4MousePressed(evt);
            }
        });
        wb.add(Close4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize4MousePressed(evt);
            }
        });
        wb.add(Minimize4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        nxe6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxe6MousePressed(evt);
            }
        });
        wb.add(nxe6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        cma1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cma1MousePressed(evt);
            }
        });
        wb.add(cma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 80, 30, 30));

        bwa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bwa1MousePressed(evt);
            }
        });
        wb.add(bwa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 80, 30, 30));

        asa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asa1MousePressed(evt);
            }
        });
        wb.add(asa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 40, 30));

        wnb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/White_Int.png"))); // NOI18N
        wb.add(wnb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Interior_WB.add(wb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_order.add(Interior_WB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Interior_C.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cream.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close9MousePressed(evt);
            }
        });
        cream.add(Close9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize9MousePressed(evt);
            }
        });
        cream.add(Minimize9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        nxe7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxe7MousePressed(evt);
            }
        });
        cream.add(nxe7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        cma2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cma2MousePressed(evt);
            }
        });
        cream.add(cma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 80, 30, 30));

        bwa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bwa2MousePressed(evt);
            }
        });
        cream.add(bwa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 80, 30, 30));

        asa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asa2MousePressed(evt);
            }
        });
        cream.add(asa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 40, 30));

        back_cream.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/Cream.png"))); // NOI18N
        cream.add(back_cream, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Interior_C.add(cream, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main_order.add(Interior_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Base_Auto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close10MousePressed(evt);
            }
        });
        Base_Auto.add(Close10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize10MousePressed(evt);
            }
        });
        Base_Auto.add(Minimize10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setBorder(null);
        Base_Auto.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 460, 20, 30));

        nxp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxpMousePressed(evt);
            }
        });
        Base_Auto.add(nxp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        Background_Auto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/Auto.gif"))); // NOI18N
        Base_Auto.add(Background_Auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout AutopilotLayout = new javax.swing.GroupLayout(Autopilot);
        Autopilot.setLayout(AutopilotLayout);
        AutopilotLayout.setHorizontalGroup(
            AutopilotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base_Auto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AutopilotLayout.setVerticalGroup(
            AutopilotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base_Auto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_order.add(Autopilot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-.png"))); // NOI18N
        Close11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close11MousePressed(evt);
            }
        });
        pay.add(Close11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 29));

        Minimize11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus-symbol.png"))); // NOI18N
        Minimize11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize11MousePressed(evt);
            }
        });
        pay.add(Minimize11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 29));

        nxpay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nxpayMousePressed(evt);
            }
        });
        pay.add(nxpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 220, 20));

        Background_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order_S/Payment.png"))); // NOI18N
        pay.add(Background_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout PaymentLayout = new javax.swing.GroupLayout(Payment);
        Payment.setLayout(PaymentLayout);
        PaymentLayout.setHorizontalGroup(
            PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PaymentLayout.setVerticalGroup(
            PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_order.add(Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Order_Platform.add(main_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(Order_Platform, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CloseMousePressed

    private void MinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMousePressed

    private void Close8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close8MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close8MousePressed

    private void Minimize8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize8MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize8MousePressed

    private void Close6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close6MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close6MousePressed

    private void Minimize6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize6MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize6MousePressed

    private void Close5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close5MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close5MousePressed

    private void Minimize5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize5MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize5MousePressed

    private void Close7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close7MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close7MousePressed

    private void Minimize7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize7MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize7MousePressed

    private void Close3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close3MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close3MousePressed

    private void Minimize3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize3MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize3MousePressed

    private void Close2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close2MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close2MousePressed

    private void Minimize2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize2MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize2MousePressed

    private void Close1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close1MousePressed

    private void Minimize1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize1MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize1MousePressed

    private void Order_PlatformMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Order_PlatformMouseDragged
        // Drag:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_Order_PlatformMouseDragged

    private void Order_PlatformMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Order_PlatformMousePressed
        // Press Drag:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_Order_PlatformMousePressed

    private void Close4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close4MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close4MousePressed

    private void Minimize4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize4MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize4MousePressed

    private void Close9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close9MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close9MousePressed

    private void Minimize9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize9MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize9MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Window Opener:
        try{
                    main_order.removeAll();
                    main_order.repaint();
                    main_order.revalidate();

                    main_order.add(Long);
                    main_order.repaint();
                    main_order.revalidate();
               }catch(Exception e){
                 
               }
    }//GEN-LAST:event_formWindowOpened

    private void pfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfMousePressed
        // set active to Performance
        active="Performance";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Performance);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_pfMousePressed

    private void lgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMousePressed
        // set active to Long
        active="Long";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Long);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_lgMousePressed

    private void nxiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxiMousePressed
        // set active to White
        active="White";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(White);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxiMousePressed

    private void nxeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxeMousePressed
        // set active to White
        active="Interior_A";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Interior_A);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxeMousePressed

    private void nxi1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxi1MousePressed
        // set active to White
        active="White";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(White);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxi1MousePressed

    private void wsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wsMousePressed
        // set active to White
        active="White";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(White);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_wsMousePressed

    private void bsmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsmMousePressed
        // set active to Solid_Black
        active="Solid_Black";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Solid_Black);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_bsmMousePressed

    private void msMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msMousePressed
        // set active to Midnight_Silver
        active="Midnight_Silver";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Midnight_Silver);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_msMousePressed

    private void dbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbMousePressed
        // set active to Blue:
        active="Blue";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Blue);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_dbMousePressed

    private void rsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rsMousePressed
        // set active to Red:
        active="Red";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Red);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_rsMousePressed

    private void rs4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rs4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rs4MousePressed

    private void db4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db4MousePressed
        //  set active to Blue:
        active="Blue";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Blue);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_db4MousePressed

    private void ms4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ms4MousePressed
        // set active to Midnight_Silver
        active="Midnight_Silver";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Midnight_Silver);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_ms4MousePressed

    private void bsm4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsm4MousePressed
        // set active to Solid_Black
        active="Solid_Black";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Solid_Black);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_bsm4MousePressed

    private void ws4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ws4MousePressed
        // set active to White
        active="White";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(White);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_ws4MousePressed

    private void rs5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rs5MousePressed
        // set active to Red:
        active="Red";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Red);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_rs5MousePressed

    private void db5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db5MousePressed
        // set active to Blue:
        active="Blue";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Blue);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_db5MousePressed

    private void ms5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ms5MousePressed
        // set active to Midnight_Silver
        active="Midnight_Silver";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Midnight_Silver);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_ms5MousePressed

    private void bsm5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsm5MousePressed
        // set active to Solid_Black
        active="Solid_Black";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Solid_Black);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_bsm5MousePressed

    private void ws5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ws5MousePressed
        // set active to White
        active="White";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(White);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_ws5MousePressed

    private void rs6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rs6MousePressed
        // set active to Red:
        active="Red";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Red);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_rs6MousePressed

    private void db6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db6MousePressed
        //  set active to Blue:
        active="Blue";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Blue);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_db6MousePressed

    private void ms6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ms6MousePressed
        // set active to Midnight_Silver
        active="Midnight_Silver";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Midnight_Silver);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_ms6MousePressed

    private void bsm6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsm6MousePressed
        // set active to Solid_Black
        active="Solid_Black";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Solid_Black);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_bsm6MousePressed

    private void ws6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ws6MousePressed
        // set active to White
        active="White";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(White);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_ws6MousePressed

    private void rs7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rs7MousePressed
        // set active to Red:
        active="Red";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Red);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_rs7MousePressed

    private void db7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db7MousePressed
        // set active to Blue:
        active="Blue";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Blue);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_db7MousePressed

    private void ms7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ms7MousePressed
        // set active to Midnight_Silver
        active="Midnight_Silver";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Midnight_Silver);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_ms7MousePressed

    private void bsm7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsm7MousePressed
        // set active to Solid_Black
        active="Solid_Black";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Solid_Black);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_bsm7MousePressed

    private void ws7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ws7MousePressed
        // set active to White
        active="White";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(White);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_ws7MousePressed

    private void nxe1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxe1MousePressed
        // set active to Interior_A
        active="White";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Interior_A);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxe1MousePressed

    private void nxe2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxe2MousePressed
        // set active to Interior_A
        active="White";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Interior_A);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxe2MousePressed

    private void nxe3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxe3MousePressed
        // set active to Interior_A
        active="Interior_A";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Interior_A);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxe3MousePressed

    private void nxe4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxe4MousePressed
        // set active to Interior_A
        active="White";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Interior_A);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxe4MousePressed

    private void asaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asaMousePressed
        // set active to Ash
        active="Ash";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Ash);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_asaMousePressed

    private void bwaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bwaMousePressed
        // set active to Interior_WB
        active="Interior_WB";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Interior_WB);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_bwaMousePressed

    private void cmaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmaMousePressed
        // set active to Interior_C
        active="Interior_C";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Interior_C);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_cmaMousePressed

    private void cma1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cma1MousePressed
        // set active to Interior_C
        active="Interior_C";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Interior_C);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_cma1MousePressed

    private void bwa1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bwa1MousePressed
        // set active to Interior_WB
        active="Interior_WB";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Interior_WB);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_bwa1MousePressed

    private void asa1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asa1MousePressed
        // set active to Ash
        active="Ash";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Ash);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_asa1MousePressed

    private void cma2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cma2MousePressed
        // set active to Interior_C
        active="Interior_C";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Interior_C);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_cma2MousePressed

    private void bwa2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bwa2MousePressed
        // set active to Interior_WB
        active="Interior_WB";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Interior_WB);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_bwa2MousePressed

    private void asa2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asa2MousePressed
        // set active to Ash
        active="Ash";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Ash);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_asa2MousePressed

    private void nxe5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxe5MousePressed
        // set active to Autopilot
        active="Autopilot";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Autopilot);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxe5MousePressed

    private void nxe6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxe6MousePressed
        // set active to Autopilot
        active="Autopilot";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Autopilot);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxe6MousePressed

    private void nxe7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxe7MousePressed
        // set active to Autopilot
        active="Autopilot";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Autopilot);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxe7MousePressed

    private void Close10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close10MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close10MousePressed

    private void Minimize10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Minimize10MousePressed

    private void nxpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxpMousePressed
        // set active to Payment
        active="Payment";
        try{
            main_order.removeAll();
            main_order.repaint();
            main_order.revalidate();
            //adding the target pannel
            main_order.add(Payment);
            main_order.repaint();
            main_order.revalidate();
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxpMousePressed

    private void Close11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close11MousePressed
        // Close:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close11MousePressed

    private void Minimize11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize11MousePressed
        // Minimize:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize11MousePressed

    private void nxpayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxpayMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nxpayMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_S().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ash;
    private javax.swing.JPanel Autopilot;
    private javax.swing.JLabel Back_Black;
    private javax.swing.JLabel Back_Blue;
    private javax.swing.JLabel Back_MS;
    private javax.swing.JLabel Back_P;
    private javax.swing.JLabel Back_W;
    private javax.swing.JLabel Back_red;
    private javax.swing.JLabel Background_Auto;
    private javax.swing.JLabel Background_L;
    private javax.swing.JLabel Background_P;
    private javax.swing.JPanel Base_Auto;
    private javax.swing.JPanel Base_L;
    private javax.swing.JPanel Base_P;
    private javax.swing.JPanel Blue;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Close1;
    private javax.swing.JLabel Close10;
    private javax.swing.JLabel Close11;
    private javax.swing.JLabel Close2;
    private javax.swing.JLabel Close3;
    private javax.swing.JLabel Close4;
    private javax.swing.JLabel Close5;
    private javax.swing.JLabel Close6;
    private javax.swing.JLabel Close7;
    private javax.swing.JLabel Close8;
    private javax.swing.JLabel Close9;
    private javax.swing.JPanel Interior_A;
    private javax.swing.JPanel Interior_C;
    private javax.swing.JPanel Interior_WB;
    private javax.swing.JPanel Long;
    private javax.swing.JPanel Midnight_Silver;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Minimize1;
    private javax.swing.JLabel Minimize10;
    private javax.swing.JLabel Minimize11;
    private javax.swing.JLabel Minimize2;
    private javax.swing.JLabel Minimize3;
    private javax.swing.JLabel Minimize4;
    private javax.swing.JLabel Minimize5;
    private javax.swing.JLabel Minimize6;
    private javax.swing.JLabel Minimize7;
    private javax.swing.JLabel Minimize8;
    private javax.swing.JLabel Minimize9;
    private javax.swing.JPanel Order_Platform;
    private javax.swing.JPanel Payment;
    private javax.swing.JPanel Performance;
    private javax.swing.JPanel Red;
    private javax.swing.JPanel Solid_Black;
    private javax.swing.JPanel White;
    private javax.swing.JLabel asa;
    private javax.swing.JLabel asa1;
    private javax.swing.JLabel asa2;
    private javax.swing.JLabel ash_wood;
    private javax.swing.JLabel back_cream;
    private javax.swing.JLabel bsm;
    private javax.swing.JLabel bsm4;
    private javax.swing.JLabel bsm5;
    private javax.swing.JLabel bsm6;
    private javax.swing.JLabel bsm7;
    private javax.swing.JLabel bwa;
    private javax.swing.JLabel bwa1;
    private javax.swing.JLabel bwa2;
    private javax.swing.JLabel cma;
    private javax.swing.JLabel cma1;
    private javax.swing.JLabel cma2;
    private javax.swing.JPanel colour_black;
    private javax.swing.JPanel colour_blue;
    private javax.swing.JPanel colour_midnight;
    private javax.swing.JPanel colour_red;
    private javax.swing.JPanel colour_w;
    private javax.swing.JPanel cream;
    private javax.swing.JLabel db;
    private javax.swing.JLabel db4;
    private javax.swing.JLabel db5;
    private javax.swing.JLabel db6;
    private javax.swing.JLabel db7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel lg;
    private javax.swing.JPanel main_order;
    private javax.swing.JLabel ms;
    private javax.swing.JLabel ms4;
    private javax.swing.JLabel ms5;
    private javax.swing.JLabel ms6;
    private javax.swing.JLabel ms7;
    private javax.swing.JLabel nxe;
    private javax.swing.JLabel nxe1;
    private javax.swing.JLabel nxe2;
    private javax.swing.JLabel nxe3;
    private javax.swing.JLabel nxe4;
    private javax.swing.JLabel nxe5;
    private javax.swing.JLabel nxe6;
    private javax.swing.JLabel nxe7;
    private javax.swing.JLabel nxi;
    private javax.swing.JLabel nxi1;
    private javax.swing.JLabel nxp;
    private javax.swing.JLabel nxpay;
    private javax.swing.JPanel pay;
    private javax.swing.JLabel pf;
    private javax.swing.JLabel rs;
    private javax.swing.JLabel rs4;
    private javax.swing.JLabel rs5;
    private javax.swing.JLabel rs6;
    private javax.swing.JLabel rs7;
    private javax.swing.JPanel wb;
    private javax.swing.JLabel wnb;
    private javax.swing.JLabel ws;
    private javax.swing.JLabel ws4;
    private javax.swing.JLabel ws5;
    private javax.swing.JLabel ws6;
    private javax.swing.JLabel ws7;
    // End of variables declaration//GEN-END:variables
}
